// Mock data for CCOS (Client Conversion OS)
// Two influencer clients: Keith and Tyson
// Coaches: Ignacio, Fatima, Waleed, Stef, Farrukh
// Closers: Jacob Broz, Will
// Onboarding: Nicole
// Setters: 4 DM setters (2 per client)

// ============================================================================
// LEGACY EXPORTS – preserved for backward compatibility with existing pages
// ============================================================================

export const CLIENTS = {
  keith: { name: "Keith", color: "#8b5cf6", stripeAccounts: 1 },
  tyson: { name: "Tyson", color: "#06b6d4", stripeAccounts: 2 },
} as const;

export const revenueData = {
  keith: {
    thisMonth: 38_200,
    lastMonth: 28_600,
    mrr: 38_200,
    totalCustomers: 49,
    activeSubscriptions: 42,
    churnRate: 3.8,
    avgRevenuePerUser: 909,
  },
  tyson: {
    account1: { thisMonth: 22_400, lastMonth: 16_800 },
    account2: { thisMonth: 9_300, lastMonth: 7_191 },
    combined: {
      thisMonth: 31_700,
      lastMonth: 23_991,
      mrr: 31_700,
      totalCustomers: 46,
      activeSubscriptions: 40,
      churnRate: 3.2,
      avgRevenuePerUser: 793,
    },
  },
  total: {
    thisMonth: 69_900,
    lastMonth: 52_591,
    growthPercent: 32.9,
  },
};

export const monthlyRevenue = [
  { month: "Sep", keith: 8200, tyson: 5100, total: 13300 },
  { month: "Oct", keith: 12400, tyson: 8900, total: 21300 },
  { month: "Nov", keith: 16800, tyson: 12200, total: 29000 },
  { month: "Dec", keith: 19500, tyson: 15800, total: 35300 },
  { month: "Jan", keith: 28600, tyson: 23991, total: 52591 },
  { month: "Feb", keith: 38200, tyson: 31700, total: 69900 },
];

export const salesFunnel = {
  keith: {
    leadsGenerated: 420,
    applicationsReceived: 126,
    callsBooked: 54,
    callsCompleted: 45,
    salesClosed: 29,
    conversionRates: {
      leadToApplication: 30.0,
      applicationToCall: 42.9,
      callBookedToCompleted: 83.3,
      callToClose: 64.4,
      overallLeadToClose: 6.9,
    },
  },
  tyson: {
    leadsGenerated: 354,
    applicationsReceived: 107,
    callsBooked: 45,
    callsCompleted: 38,
    salesClosed: 24,
    conversionRates: {
      leadToApplication: 30.2,
      applicationToCall: 42.1,
      callBookedToCompleted: 84.4,
      callToClose: 63.2,
      overallLeadToClose: 6.8,
    },
  },
};

export const funnelStages = [
  { stage: "Messages", keith: 420, tyson: 354 },

  { stage: "60-min Booked", keith: 44, tyson: 36 },
  { stage: "60-min Taken", keith: 35, tyson: 28 },
  { stage: "Closed", keith: 29, tyson: 24 },
];

export const adPerformance = {
  keith: {
    spend: 2_130,
    impressions: 179_500,
    clicks: 2_392,
    leads: 420,
    cpl: 5.07,
    ctr: 1.33,
    cpc: 0.89,
    roas: 17.93,
    revenue: 38_200,
  },
  tyson: {
    spend: 1_743,
    impressions: 146_700,
    clicks: 1_952,
    leads: 354,
    cpl: 4.92,
    ctr: 1.33,
    cpc: 0.89,
    roas: 18.19,
    revenue: 31_700,
  },
};

export const adSpendTrend = [
  { month: "Sep", keith: 720, tyson: 580 },
  { month: "Oct", keith: 980, tyson: 820 },
  { month: "Nov", keith: 1250, tyson: 1050 },
  { month: "Dec", keith: 1480, tyson: 1220 },
  { month: "Jan", keith: 1900, tyson: 1549 },
  { month: "Feb", keith: 2130, tyson: 1743 },
];

export const coachingData = {
  keith: {
    activeClients: 49,
    onboarding: 4,
    completedOnboarding: 45,
    avgSatisfaction: 8.9,
    reviewsCount: 38,
    healthCoaches: 3,
    clientRetention: 93,
  },
  tyson: {
    activeClients: 46,
    onboarding: 3,
    completedOnboarding: 43,
    avgSatisfaction: 8.6,
    reviewsCount: 34,
    healthCoaches: 3,
    clientRetention: 91,
  },
};

export const recentReviews = [
  {
    client: "Marcus R.",
    rating: 5,
    text: "Ignacio keeps me on track. Hit a squat PR this week!",
    source: "keith",
    date: "Feb 19",
  },
  {
    client: "Jasmine O.",
    rating: 5,
    text: "Fatima adjusted my macros for Ramadan and I still lost weight.",
    source: "keith",
    date: "Feb 18",
  },
  {
    client: "Rachel F.",
    rating: 5,
    text: "Josh created a home workout plan that works perfectly.",
    source: "keith",
    date: "Feb 17",
  },
  {
    client: "Angela C.",
    rating: 4,
    text: "Mark fixed my hip hinge form. Deadlifts feel great now.",
    source: "tyson",
    date: "Feb 15",
  },
];

export const satisfactionTrend = [
  { week: "Jan 6", avgRating: 8.1 },
  { week: "Jan 13", avgRating: 8.4 },
  { week: "Jan 20", avgRating: 8.2 },
  { week: "Jan 27", avgRating: 8.6 },
  { week: "Feb 3", avgRating: 8.5 },
  { week: "Feb 10", avgRating: 8.8 },
  { week: "Feb 17", avgRating: 8.7 },
];

export const slackActivity = [
  {
    channel: "#general",
    message: "Team standup notes posted",
    user: "Alex",
    time: "9:15 AM",
  },
  {
    channel: "#sales",
    message: "3 new applications came in overnight",
    user: "Matt",
    time: "8:42 AM",
  },
  {
    channel: "#coaching",
    message: "Client Marcus R. hit a squat PR!",
    user: "Ignacio",
    time: "8:30 AM",
  },
  {
    channel: "#ads",
    message: "Feb ROI running at 1364% - best month yet",
    user: "Alex",
    time: "7:55 AM",
  },
  {
    channel: "#general",
    message: "Weekly metrics review at 2pm today",
    user: "Alex",
    time: "7:30 AM",
  },
];

export const constraintAnalysis = {
  primaryConstraint: {
    area: "Waleed's Client Completion Rate",
    metric: "72%",
    benchmark: "85%+",
    impact:
      "Improving to 85% would reduce churn and add ~$3,200/mo in retained revenue",
    severity: "warning" as const,
  },
  opportunities: [
    {
      action: "Increase ad spend 30-50% while ROI is above 1300%",
      impact: "+$15,000-25,000/mo",
      effort: "Low",
      leverageScore: 9.5,
    },
    {
      action: "Add 2 coaches to unlock capacity for 40 more clients",
      impact: "+$40,000/mo potential",
      effort: "Medium",
      leverageScore: 9.2,
    },
    {
      action: "Launch referral program - clients already sharing results",
      impact: "+$8,000/mo",
      effort: "Low",
      leverageScore: 8.8,
    },
    {
      action: "Implement no-show recovery sequence for 60-min calls",
      impact: "+$4,200/mo",
      effort: "Low",
      leverageScore: 8.5,
    },
    {
      action: "Waleed coaching improvement plan to match team avg",
      impact: "Reduce churn by 4-6 clients/mo",
      effort: "Medium",
      leverageScore: 8.0,
    },
  ],
  businessHealth: {
    score: 82,
    trend: "up" as const,
    lastMonth: 76,
  },
};

// ============================================================================
// 1. adsData – Daily ads tracker for Jan & Feb 2026
// ============================================================================

export interface AdsDayEntry {
  date: string;
  adSpend: number;
  impressions: number;
  cpi: number;
  linkClicks: number;
  ctr: number;
  cpc: number;
  messages: number;
  costPerMessage: number;
  calls60Booked: number;
  costPer60Booked: number;
  calls60Taken: number;
  showUp60Pct: number;
  newClients: number;
  closeRate: number;
  msgConversionRate: number;
  contractedRevenue: number;
  collectedRevenue: number;
  costPerClient: number;
  contractedROI: number;
  collectedROI: number;
}

export const adsData: AdsDayEntry[] = [
  // ---- JANUARY 2026 ----
  {
    date: "2026-01-01",
    adSpend: 98,
    impressions: 8420,
    cpi: 11.64,
    linkClicks: 112,
    ctr: 1.33,
    cpc: 0.88,
    messages: 18,
    costPerMessage: 5.44,    calls60Booked: 1,
    costPer60Booked: 98.0,
    calls60Taken: 1,
    showUp60Pct: 100.0,
    newClients: 1,
    closeRate: 100.0,
    msgConversionRate: 5.56,
    contractedRevenue: 1200,
    collectedRevenue: 600,
    costPerClient: 98.0,
    contractedROI: 1124.49,
    collectedROI: 512.24,
  },
  {
    date: "2026-01-02",
    adSpend: 105,
    impressions: 9100,
    cpi: 11.54,
    linkClicks: 121,
    ctr: 1.33,
    cpc: 0.87,
    messages: 20,
    costPerMessage: 5.25,    calls60Booked: 2,
    costPer60Booked: 52.5,
    calls60Taken: 1,
    showUp60Pct: 50.0,
    newClients: 1,
    closeRate: 100.0,
    msgConversionRate: 10.0,
    contractedRevenue: 1500,
    collectedRevenue: 750,
    costPerClient: 105.0,
    contractedROI: 1328.57,
    collectedROI: 614.29,
  },
  {
    date: "2026-01-03",
    adSpend: 112,
    impressions: 9800,
    cpi: 11.43,
    linkClicks: 134,
    ctr: 1.37,
    cpc: 0.84,
    messages: 22,
    costPerMessage: 5.09,    calls60Booked: 2,
    costPer60Booked: 56.0,
    calls60Taken: 2,
    showUp60Pct: 100.0,
    newClients: 1,
    closeRate: 50.0,
    msgConversionRate: 9.09,
    contractedRevenue: 1200,
    collectedRevenue: 1200,
    costPerClient: 112.0,
    contractedROI: 971.43,
    collectedROI: 971.43,
  },
  {
    date: "2026-01-04",
    adSpend: 95,
    impressions: 8200,
    cpi: 11.59,
    linkClicks: 108,
    ctr: 1.32,
    cpc: 0.88,
    messages: 16,
    costPerMessage: 5.94,    calls60Booked: 1,
    costPer60Booked: 95.0,
    calls60Taken: 1,
    showUp60Pct: 100.0,
    newClients: 1,
    closeRate: 100.0,
    msgConversionRate: 6.25,
    contractedRevenue: 997,
    collectedRevenue: 997,
    costPerClient: 95.0,
    contractedROI: 949.47,
    collectedROI: 949.47,
  },
  {
    date: "2026-01-05",
    adSpend: 118,
    impressions: 10500,
    cpi: 11.24,
    linkClicks: 142,
    ctr: 1.35,
    cpc: 0.83,
    messages: 24,
    costPerMessage: 4.92,    calls60Booked: 2,
    costPer60Booked: 59.0,
    calls60Taken: 2,
    showUp60Pct: 100.0,
    newClients: 2,
    closeRate: 100.0,
    msgConversionRate: 8.33,
    contractedRevenue: 2400,
    collectedRevenue: 1200,
    costPerClient: 59.0,
    contractedROI: 1933.9,
    collectedROI: 916.95,
  },
  {
    date: "2026-01-06",
    adSpend: 130,
    impressions: 11200,
    cpi: 11.61,
    linkClicks: 148,
    ctr: 1.32,
    cpc: 0.88,
    messages: 26,
    costPerMessage: 5.0,    calls60Booked: 3,
    costPer60Booked: 43.33,
    calls60Taken: 2,
    showUp60Pct: 66.67,
    newClients: 2,
    closeRate: 100.0,
    msgConversionRate: 7.69,
    contractedRevenue: 2200,
    collectedRevenue: 1100,
    costPerClient: 65.0,
    contractedROI: 1592.31,
    collectedROI: 746.15,
  },
  {
    date: "2026-01-07",
    adSpend: 108,
    impressions: 9400,
    cpi: 11.49,
    linkClicks: 125,
    ctr: 1.33,
    cpc: 0.86,
    messages: 19,
    costPerMessage: 5.68,    calls60Booked: 2,
    costPer60Booked: 54.0,
    calls60Taken: 1,
    showUp60Pct: 50.0,
    newClients: 1,
    closeRate: 100.0,
    msgConversionRate: 10.53,
    contractedRevenue: 1500,
    collectedRevenue: 500,
    costPerClient: 108.0,
    contractedROI: 1288.89,
    collectedROI: 362.96,
  },
  {
    date: "2026-01-08",
    adSpend: 115,
    impressions: 10100,
    cpi: 11.39,
    linkClicks: 137,
    ctr: 1.36,
    cpc: 0.84,
    messages: 23,
    costPerMessage: 5.0,    calls60Booked: 2,
    costPer60Booked: 57.5,
    calls60Taken: 2,
    showUp60Pct: 100.0,
    newClients: 1,
    closeRate: 50.0,
    msgConversionRate: 8.7,
    contractedRevenue: 1200,
    collectedRevenue: 1200,
    costPerClient: 115.0,
    contractedROI: 943.48,
    collectedROI: 943.48,
  },
  {
    date: "2026-01-09",
    adSpend: 122,
    impressions: 10800,
    cpi: 11.3,
    linkClicks: 146,
    ctr: 1.35,
    cpc: 0.84,
    messages: 25,
    costPerMessage: 4.88,    calls60Booked: 3,
    costPer60Booked: 40.67,
    calls60Taken: 2,
    showUp60Pct: 66.67,
    newClients: 2,
    closeRate: 100.0,
    msgConversionRate: 12.0,
    contractedRevenue: 2800,
    collectedRevenue: 1400,
    costPerClient: 61.0,
    contractedROI: 2195.08,
    collectedROI: 1047.54,
  },
  {
    date: "2026-01-10",
    adSpend: 100,
    impressions: 8700,
    cpi: 11.49,
    linkClicks: 115,
    ctr: 1.32,
    cpc: 0.87,
    messages: 17,
    costPerMessage: 5.88,    calls60Booked: 1,
    costPer60Booked: 100.0,
    calls60Taken: 1,
    showUp60Pct: 100.0,
    newClients: 1,
    closeRate: 100.0,
    msgConversionRate: 5.88,
    contractedRevenue: 997,
    collectedRevenue: 997,
    costPerClient: 100.0,
    contractedROI: 897.0,
    collectedROI: 897.0,
  },
  {
    date: "2026-01-11",
    adSpend: 88,
    impressions: 7600,
    cpi: 11.58,
    linkClicks: 100,
    ctr: 1.32,
    cpc: 0.88,
    messages: 14,
    costPerMessage: 6.29,    calls60Booked: 1,
    costPer60Booked: 88.0,
    calls60Taken: 1,
    showUp60Pct: 100.0,
    newClients: 0,
    closeRate: 0.0,
    msgConversionRate: 7.14,
    contractedRevenue: 0,
    collectedRevenue: 0,
    costPerClient: 0,
    contractedROI: -100.0,
    collectedROI: -100.0,
  },
  {
    date: "2026-01-12",
    adSpend: 135,
    impressions: 12000,
    cpi: 11.25,
    linkClicks: 160,
    ctr: 1.33,
    cpc: 0.84,
    messages: 28,
    costPerMessage: 4.82,    calls60Booked: 3,
    costPer60Booked: 45.0,
    calls60Taken: 3,
    showUp60Pct: 100.0,
    newClients: 2,
    closeRate: 66.67,
    msgConversionRate: 10.71,
    contractedRevenue: 2700,
    collectedRevenue: 1800,
    costPerClient: 67.5,
    contractedROI: 1900.0,
    collectedROI: 1233.33,
  },
  {
    date: "2026-01-13",
    adSpend: 110,
    impressions: 9600,
    cpi: 11.46,
    linkClicks: 128,
    ctr: 1.33,
    cpc: 0.86,
    messages: 21,
    costPerMessage: 5.24,    calls60Booked: 2,
    costPer60Booked: 55.0,
    calls60Taken: 2,
    showUp60Pct: 100.0,
    newClients: 1,
    closeRate: 50.0,
    msgConversionRate: 9.52,
    contractedRevenue: 1500,
    collectedRevenue: 750,
    costPerClient: 110.0,
    contractedROI: 1263.64,
    collectedROI: 581.82,
  },
  {
    date: "2026-01-14",
    adSpend: 125,
    impressions: 11000,
    cpi: 11.36,
    linkClicks: 147,
    ctr: 1.34,
    cpc: 0.85,
    messages: 25,
    costPerMessage: 5.0,    calls60Booked: 2,
    costPer60Booked: 62.5,
    calls60Taken: 2,
    showUp60Pct: 100.0,
    newClients: 2,
    closeRate: 100.0,
    msgConversionRate: 8.0,
    contractedRevenue: 2400,
    collectedRevenue: 1200,
    costPerClient: 62.5,
    contractedROI: 1820.0,
    collectedROI: 860.0,
  },
  {
    date: "2026-01-15",
    adSpend: 120,
    impressions: 10600,
    cpi: 11.32,
    linkClicks: 141,
    ctr: 1.33,
    cpc: 0.85,
    messages: 24,
    costPerMessage: 5.0,    calls60Booked: 2,
    costPer60Booked: 60.0,
    calls60Taken: 2,
    showUp60Pct: 100.0,
    newClients: 2,
    closeRate: 100.0,
    msgConversionRate: 8.33,
    contractedRevenue: 2200,
    collectedRevenue: 2200,
    costPerClient: 60.0,
    contractedROI: 1733.33,
    collectedROI: 1733.33,
  },
  {
    date: "2026-01-16",
    adSpend: 115,
    impressions: 10000,
    cpi: 11.5,
    linkClicks: 133,
    ctr: 1.33,
    cpc: 0.86,
    messages: 22,
    costPerMessage: 5.23,    calls60Booked: 2,
    costPer60Booked: 57.5,
    calls60Taken: 2,
    showUp60Pct: 100.0,
    newClients: 1,
    closeRate: 50.0,
    msgConversionRate: 9.09,
    contractedRevenue: 1500,
    collectedRevenue: 750,
    costPerClient: 115.0,
    contractedROI: 1204.35,
    collectedROI: 552.17,
  },
  {
    date: "2026-01-17",
    adSpend: 102,
    impressions: 8900,
    cpi: 11.46,
    linkClicks: 118,
    ctr: 1.33,
    cpc: 0.86,
    messages: 19,
    costPerMessage: 5.37,    calls60Booked: 2,
    costPer60Booked: 51.0,
    calls60Taken: 1,
    showUp60Pct: 50.0,
    newClients: 1,
    closeRate: 100.0,
    msgConversionRate: 10.53,
    contractedRevenue: 1200,
    collectedRevenue: 600,
    costPerClient: 102.0,
    contractedROI: 1076.47,
    collectedROI: 488.24,
  },
  {
    date: "2026-01-18",
    adSpend: 90,
    impressions: 7800,
    cpi: 11.54,
    linkClicks: 103,
    ctr: 1.32,
    cpc: 0.87,
    messages: 15,
    costPerMessage: 6.0,    calls60Booked: 1,
    costPer60Booked: 90.0,
    calls60Taken: 1,
    showUp60Pct: 100.0,
    newClients: 1,
    closeRate: 100.0,
    msgConversionRate: 6.67,
    contractedRevenue: 997,
    collectedRevenue: 997,
    costPerClient: 90.0,
    contractedROI: 1007.78,
    collectedROI: 1007.78,
  },
  {
    date: "2026-01-19",
    adSpend: 128,
    impressions: 11300,
    cpi: 11.33,
    linkClicks: 150,
    ctr: 1.33,
    cpc: 0.85,
    messages: 27,
    costPerMessage: 4.74,    calls60Booked: 3,
    costPer60Booked: 42.67,
    calls60Taken: 2,
    showUp60Pct: 66.67,
    newClients: 2,
    closeRate: 100.0,
    msgConversionRate: 11.11,
    contractedRevenue: 2800,
    collectedRevenue: 1400,
    costPerClient: 64.0,
    contractedROI: 2087.5,
    collectedROI: 993.75,
  },
  {
    date: "2026-01-20",
    adSpend: 118,
    impressions: 10400,
    cpi: 11.35,
    linkClicks: 138,
    ctr: 1.33,
    cpc: 0.86,
    messages: 23,
    costPerMessage: 5.13,    calls60Booked: 2,
    costPer60Booked: 59.0,
    calls60Taken: 2,
    showUp60Pct: 100.0,
    newClients: 1,
    closeRate: 50.0,
    msgConversionRate: 8.7,
    contractedRevenue: 1500,
    collectedRevenue: 1500,
    costPerClient: 118.0,
    contractedROI: 1171.19,
    collectedROI: 1171.19,
  },
  {
    date: "2026-01-21",
    adSpend: 132,
    impressions: 11600,
    cpi: 11.38,
    linkClicks: 155,
    ctr: 1.34,
    cpc: 0.85,
    messages: 28,
    costPerMessage: 4.71,    calls60Booked: 3,
    costPer60Booked: 44.0,
    calls60Taken: 3,
    showUp60Pct: 100.0,
    newClients: 2,
    closeRate: 66.67,
    msgConversionRate: 10.71,
    contractedRevenue: 2700,
    collectedRevenue: 1800,
    costPerClient: 66.0,
    contractedROI: 1945.45,
    collectedROI: 1263.64,
  },
  {
    date: "2026-01-22",
    adSpend: 110,
    impressions: 9600,
    cpi: 11.46,
    linkClicks: 128,
    ctr: 1.33,
    cpc: 0.86,
    messages: 21,
    costPerMessage: 5.24,    calls60Booked: 2,
    costPer60Booked: 55.0,
    calls60Taken: 2,
    showUp60Pct: 100.0,
    newClients: 1,
    closeRate: 50.0,
    msgConversionRate: 9.52,
    contractedRevenue: 1200,
    collectedRevenue: 1200,
    costPerClient: 110.0,
    contractedROI: 990.91,
    collectedROI: 990.91,
  },
  {
    date: "2026-01-23",
    adSpend: 125,
    impressions: 11000,
    cpi: 11.36,
    linkClicks: 147,
    ctr: 1.34,
    cpc: 0.85,
    messages: 25,
    costPerMessage: 5.0,    calls60Booked: 3,
    costPer60Booked: 41.67,
    calls60Taken: 2,
    showUp60Pct: 66.67,
    newClients: 2,
    closeRate: 100.0,
    msgConversionRate: 12.0,
    contractedRevenue: 2400,
    collectedRevenue: 1200,
    costPerClient: 62.5,
    contractedROI: 1820.0,
    collectedROI: 860.0,
  },
  {
    date: "2026-01-24",
    adSpend: 105,
    impressions: 9200,
    cpi: 11.41,
    linkClicks: 122,
    ctr: 1.33,
    cpc: 0.86,
    messages: 20,
    costPerMessage: 5.25,    calls60Booked: 2,
    costPer60Booked: 52.5,
    calls60Taken: 1,
    showUp60Pct: 50.0,
    newClients: 1,
    closeRate: 100.0,
    msgConversionRate: 10.0,
    contractedRevenue: 1500,
    collectedRevenue: 750,
    costPerClient: 105.0,
    contractedROI: 1328.57,
    collectedROI: 614.29,
  },
  {
    date: "2026-01-25",
    adSpend: 92,
    impressions: 8000,
    cpi: 11.5,
    linkClicks: 106,
    ctr: 1.33,
    cpc: 0.87,
    messages: 16,
    costPerMessage: 5.75,    calls60Booked: 1,
    costPer60Booked: 92.0,
    calls60Taken: 1,
    showUp60Pct: 100.0,
    newClients: 1,
    closeRate: 100.0,
    msgConversionRate: 6.25,
    contractedRevenue: 997,
    collectedRevenue: 997,
    costPerClient: 92.0,
    contractedROI: 983.7,
    collectedROI: 983.7,
  },
  {
    date: "2026-01-26",
    adSpend: 138,
    impressions: 12200,
    cpi: 11.31,
    linkClicks: 163,
    ctr: 1.34,
    cpc: 0.85,
    messages: 29,
    costPerMessage: 4.76,    calls60Booked: 3,
    costPer60Booked: 46.0,
    calls60Taken: 3,
    showUp60Pct: 100.0,
    newClients: 2,
    closeRate: 66.67,
    msgConversionRate: 10.34,
    contractedRevenue: 2800,
    collectedRevenue: 2100,
    costPerClient: 69.0,
    contractedROI: 1928.99,
    collectedROI: 1421.74,
  },
  {
    date: "2026-01-27",
    adSpend: 115,
    impressions: 10100,
    cpi: 11.39,
    linkClicks: 134,
    ctr: 1.33,
    cpc: 0.86,
    messages: 22,
    costPerMessage: 5.23,    calls60Booked: 2,
    costPer60Booked: 57.5,
    calls60Taken: 2,
    showUp60Pct: 100.0,
    newClients: 2,
    closeRate: 100.0,
    msgConversionRate: 9.09,
    contractedRevenue: 2200,
    collectedRevenue: 1100,
    costPerClient: 57.5,
    contractedROI: 1813.04,
    collectedROI: 856.52,
  },
  {
    date: "2026-01-28",
    adSpend: 120,
    impressions: 10500,
    cpi: 11.43,
    linkClicks: 140,
    ctr: 1.33,
    cpc: 0.86,
    messages: 24,
    costPerMessage: 5.0,    calls60Booked: 2,
    costPer60Booked: 60.0,
    calls60Taken: 2,
    showUp60Pct: 100.0,
    newClients: 2,
    closeRate: 100.0,
    msgConversionRate: 8.33,
    contractedRevenue: 2400,
    collectedRevenue: 1800,
    costPerClient: 60.0,
    contractedROI: 1900.0,
    collectedROI: 1400.0,
  },
  {
    date: "2026-01-29",
    adSpend: 108,
    impressions: 9500,
    cpi: 11.37,
    linkClicks: 126,
    ctr: 1.33,
    cpc: 0.86,
    messages: 21,
    costPerMessage: 5.14,    calls60Booked: 2,
    costPer60Booked: 54.0,
    calls60Taken: 2,
    showUp60Pct: 100.0,
    newClients: 1,
    closeRate: 50.0,
    msgConversionRate: 9.52,
    contractedRevenue: 1500,
    collectedRevenue: 750,
    costPerClient: 108.0,
    contractedROI: 1288.89,
    collectedROI: 594.44,
  },
  {
    date: "2026-01-30",
    adSpend: 125,
    impressions: 11000,
    cpi: 11.36,
    linkClicks: 146,
    ctr: 1.33,
    cpc: 0.86,
    messages: 25,
    costPerMessage: 5.0,    calls60Booked: 3,
    costPer60Booked: 41.67,
    calls60Taken: 2,
    showUp60Pct: 66.67,
    newClients: 2,
    closeRate: 100.0,
    msgConversionRate: 12.0,
    contractedRevenue: 2800,
    collectedRevenue: 1400,
    costPerClient: 62.5,
    contractedROI: 2140.0,
    collectedROI: 1020.0,
  },
  {
    date: "2026-01-31",
    adSpend: 112,
    impressions: 9800,
    cpi: 11.43,
    linkClicks: 130,
    ctr: 1.33,
    cpc: 0.86,
    messages: 22,
    costPerMessage: 5.09,    calls60Booked: 2,
    costPer60Booked: 56.0,
    calls60Taken: 2,
    showUp60Pct: 100.0,
    newClients: 1,
    closeRate: 50.0,
    msgConversionRate: 9.09,
    contractedRevenue: 1500,
    collectedRevenue: 1500,
    costPerClient: 112.0,
    contractedROI: 1239.29,
    collectedROI: 1239.29,
  },

  // ---- FEBRUARY 2026 ----
  // Feb totals target: ~$3,873 spend, ~326K impressions, ~774 messages,
  // ~99 calls booked, ~53 new clients, ~$52,835 collected, ~1364% ROI
  {
    date: "2026-02-01",
    adSpend: 145,
    impressions: 12800,
    cpi: 11.33,
    linkClicks: 170,
    ctr: 1.33,
    cpc: 0.85,
    messages: 30,
    costPerMessage: 4.83,    calls60Booked: 3,
    costPer60Booked: 48.33,
    calls60Taken: 3,
    showUp60Pct: 100.0,
    newClients: 2,
    closeRate: 66.67,
    msgConversionRate: 10.0,
    contractedRevenue: 2800,
    collectedRevenue: 2100,
    costPerClient: 72.5,
    contractedROI: 1831.03,
    collectedROI: 1348.28,
  },
  {
    date: "2026-02-02",
    adSpend: 160,
    impressions: 14200,
    cpi: 11.27,
    linkClicks: 189,
    ctr: 1.33,
    cpc: 0.85,
    messages: 33,
    costPerMessage: 4.85,    calls60Booked: 4,
    costPer60Booked: 40.0,
    calls60Taken: 3,
    showUp60Pct: 75.0,
    newClients: 3,
    closeRate: 100.0,
    msgConversionRate: 12.12,
    contractedRevenue: 3600,
    collectedRevenue: 2700,
    costPerClient: 53.33,
    contractedROI: 2150.0,
    collectedROI: 1587.5,
  },
  {
    date: "2026-02-03",
    adSpend: 172,
    impressions: 15300,
    cpi: 11.24,
    linkClicks: 204,
    ctr: 1.33,
    cpc: 0.84,
    messages: 36,
    costPerMessage: 4.78,    calls60Booked: 4,
    costPer60Booked: 43.0,
    calls60Taken: 3,
    showUp60Pct: 75.0,
    newClients: 3,
    closeRate: 100.0,
    msgConversionRate: 11.11,
    contractedRevenue: 3900,
    collectedRevenue: 2925,
    costPerClient: 57.33,
    contractedROI: 2167.44,
    collectedROI: 1600.58,
  },
  {
    date: "2026-02-04",
    adSpend: 185,
    impressions: 16500,
    cpi: 11.21,
    linkClicks: 220,
    ctr: 1.33,
    cpc: 0.84,
    messages: 38,
    costPerMessage: 4.87,    calls60Booked: 4,
    costPer60Booked: 46.25,
    calls60Taken: 3,
    showUp60Pct: 75.0,
    newClients: 3,
    closeRate: 100.0,
    msgConversionRate: 10.53,
    contractedRevenue: 3600,
    collectedRevenue: 2700,
    costPerClient: 61.67,
    contractedROI: 1845.95,
    collectedROI: 1359.46,
  },
  {
    date: "2026-02-05",
    adSpend: 195,
    impressions: 17400,
    cpi: 11.21,
    linkClicks: 232,
    ctr: 1.33,
    cpc: 0.84,
    messages: 40,
    costPerMessage: 4.88,    calls60Booked: 4,
    costPer60Booked: 48.75,
    calls60Taken: 4,
    showUp60Pct: 100.0,
    newClients: 3,
    closeRate: 75.0,
    msgConversionRate: 10.0,
    contractedRevenue: 3900,
    collectedRevenue: 2925,
    costPerClient: 65.0,
    contractedROI: 1900.0,
    collectedROI: 1400.0,
  },
  {
    date: "2026-02-06",
    adSpend: 202,
    impressions: 18000,
    cpi: 11.22,
    linkClicks: 240,
    ctr: 1.33,
    cpc: 0.84,
    messages: 42,
    costPerMessage: 4.81,    calls60Booked: 4,
    costPer60Booked: 50.5,
    calls60Taken: 4,
    showUp60Pct: 100.0,
    newClients: 3,
    closeRate: 75.0,
    msgConversionRate: 9.52,
    contractedRevenue: 3900,
    collectedRevenue: 2925,
    costPerClient: 67.33,
    contractedROI: 1830.69,
    collectedROI: 1348.02,
  },
  {
    date: "2026-02-07",
    adSpend: 178,
    impressions: 15800,
    cpi: 11.27,
    linkClicks: 210,
    ctr: 1.33,
    cpc: 0.85,
    messages: 37,
    costPerMessage: 4.81,    calls60Booked: 3,
    costPer60Booked: 59.33,
    calls60Taken: 3,
    showUp60Pct: 100.0,
    newClients: 3,
    closeRate: 100.0,
    msgConversionRate: 8.11,
    contractedRevenue: 3600,
    collectedRevenue: 2700,
    costPerClient: 59.33,
    contractedROI: 1922.47,
    collectedROI: 1416.85,
  },
  {
    date: "2026-02-08",
    adSpend: 155,
    impressions: 13800,
    cpi: 11.23,
    linkClicks: 184,
    ctr: 1.33,
    cpc: 0.84,
    messages: 32,
    costPerMessage: 4.84,    calls60Booked: 3,
    costPer60Booked: 51.67,
    calls60Taken: 2,
    showUp60Pct: 66.67,
    newClients: 2,
    closeRate: 100.0,
    msgConversionRate: 9.38,
    contractedRevenue: 2400,
    collectedRevenue: 1800,
    costPerClient: 77.5,
    contractedROI: 1448.39,
    collectedROI: 1061.29,
  },
  {
    date: "2026-02-09",
    adSpend: 188,
    impressions: 16700,
    cpi: 11.26,
    linkClicks: 223,
    ctr: 1.34,
    cpc: 0.84,
    messages: 39,
    costPerMessage: 4.82,    calls60Booked: 4,
    costPer60Booked: 47.0,
    calls60Taken: 3,
    showUp60Pct: 75.0,
    newClients: 3,
    closeRate: 100.0,
    msgConversionRate: 10.26,
    contractedRevenue: 3600,
    collectedRevenue: 2700,
    costPerClient: 62.67,
    contractedROI: 1814.89,
    collectedROI: 1336.17,
  },
  {
    date: "2026-02-10",
    adSpend: 200,
    impressions: 17800,
    cpi: 11.24,
    linkClicks: 237,
    ctr: 1.33,
    cpc: 0.84,
    messages: 41,
    costPerMessage: 4.88,    calls60Booked: 4,
    costPer60Booked: 50.0,
    calls60Taken: 3,
    showUp60Pct: 75.0,
    newClients: 3,
    closeRate: 100.0,
    msgConversionRate: 9.76,
    contractedRevenue: 3900,
    collectedRevenue: 2925,
    costPerClient: 66.67,
    contractedROI: 1850.0,
    collectedROI: 1362.5,
  },
  {
    date: "2026-02-11",
    adSpend: 210,
    impressions: 18700,
    cpi: 11.23,
    linkClicks: 249,
    ctr: 1.33,
    cpc: 0.84,
    messages: 44,
    costPerMessage: 4.77,    calls60Booked: 5,
    costPer60Booked: 42.0,
    calls60Taken: 4,
    showUp60Pct: 80.0,
    newClients: 3,
    closeRate: 75.0,
    msgConversionRate: 11.36,
    contractedRevenue: 3900,
    collectedRevenue: 2925,
    costPerClient: 70.0,
    contractedROI: 1757.14,
    collectedROI: 1292.86,
  },
  {
    date: "2026-02-12",
    adSpend: 195,
    impressions: 17300,
    cpi: 11.27,
    linkClicks: 231,
    ctr: 1.34,
    cpc: 0.84,
    messages: 40,
    costPerMessage: 4.88,    calls60Booked: 4,
    costPer60Booked: 48.75,
    calls60Taken: 3,
    showUp60Pct: 75.0,
    newClients: 3,
    closeRate: 100.0,
    msgConversionRate: 10.0,
    contractedRevenue: 3600,
    collectedRevenue: 2700,
    costPerClient: 65.0,
    contractedROI: 1746.15,
    collectedROI: 1284.62,
  },
  {
    date: "2026-02-13",
    adSpend: 182,
    impressions: 16200,
    cpi: 11.23,
    linkClicks: 216,
    ctr: 1.33,
    cpc: 0.84,
    messages: 38,
    costPerMessage: 4.79,    calls60Booked: 4,
    costPer60Booked: 45.5,
    calls60Taken: 3,
    showUp60Pct: 75.0,
    newClients: 2,
    closeRate: 66.67,
    msgConversionRate: 10.53,
    contractedRevenue: 2800,
    collectedRevenue: 2100,
    costPerClient: 91.0,
    contractedROI: 1438.46,
    collectedROI: 1053.85,
  },
  {
    date: "2026-02-14",
    adSpend: 168,
    impressions: 14900,
    cpi: 11.28,
    linkClicks: 198,
    ctr: 1.33,
    cpc: 0.85,
    messages: 35,
    costPerMessage: 4.8,    calls60Booked: 3,
    costPer60Booked: 56.0,
    calls60Taken: 3,
    showUp60Pct: 100.0,
    newClients: 2,
    closeRate: 66.67,
    msgConversionRate: 8.57,
    contractedRevenue: 2800,
    collectedRevenue: 2100,
    costPerClient: 84.0,
    contractedROI: 1566.67,
    collectedROI: 1150.0,
  },
  {
    date: "2026-02-15",
    adSpend: 205,
    impressions: 18200,
    cpi: 11.26,
    linkClicks: 243,
    ctr: 1.34,
    cpc: 0.84,
    messages: 42,
    costPerMessage: 4.88,    calls60Booked: 4,
    costPer60Booked: 51.25,
    calls60Taken: 4,
    showUp60Pct: 100.0,
    newClients: 3,
    closeRate: 75.0,
    msgConversionRate: 9.52,
    contractedRevenue: 3900,
    collectedRevenue: 2925,
    costPerClient: 68.33,
    contractedROI: 1802.44,
    collectedROI: 1326.83,
  },
  {
    date: "2026-02-16",
    adSpend: 190,
    impressions: 16900,
    cpi: 11.24,
    linkClicks: 225,
    ctr: 1.33,
    cpc: 0.84,
    messages: 39,
    costPerMessage: 4.87,    calls60Booked: 4,
    costPer60Booked: 47.5,
    calls60Taken: 3,
    showUp60Pct: 75.0,
    newClients: 3,
    closeRate: 100.0,
    msgConversionRate: 10.26,
    contractedRevenue: 3600,
    collectedRevenue: 2700,
    costPerClient: 63.33,
    contractedROI: 1794.74,
    collectedROI: 1321.05,
  },
  {
    date: "2026-02-17",
    adSpend: 215,
    impressions: 19100,
    cpi: 11.26,
    linkClicks: 254,
    ctr: 1.33,
    cpc: 0.85,
    messages: 45,
    costPerMessage: 4.78,    calls60Booked: 5,
    costPer60Booked: 43.0,
    calls60Taken: 4,
    showUp60Pct: 80.0,
    newClients: 4,
    closeRate: 100.0,
    msgConversionRate: 11.11,
    contractedRevenue: 5200,
    collectedRevenue: 3900,
    costPerClient: 53.75,
    contractedROI: 2318.6,
    collectedROI: 1713.95,
  },
  {
    date: "2026-02-18",
    adSpend: 198,
    impressions: 17600,
    cpi: 11.25,
    linkClicks: 234,
    ctr: 1.33,
    cpc: 0.85,
    messages: 41,
    costPerMessage: 4.83,    calls60Booked: 4,
    costPer60Booked: 49.5,
    calls60Taken: 3,
    showUp60Pct: 75.0,
    newClients: 3,
    closeRate: 100.0,
    msgConversionRate: 9.76,
    contractedRevenue: 3600,
    collectedRevenue: 2700,
    costPerClient: 66.0,
    contractedROI: 1718.18,
    collectedROI: 1263.64,
  },
  {
    date: "2026-02-19",
    adSpend: 208,
    impressions: 18500,
    cpi: 11.24,
    linkClicks: 246,
    ctr: 1.33,
    cpc: 0.85,
    messages: 43,
    costPerMessage: 4.84,    calls60Booked: 4,
    costPer60Booked: 52.0,
    calls60Taken: 4,
    showUp60Pct: 100.0,
    newClients: 3,
    closeRate: 75.0,
    msgConversionRate: 9.3,
    contractedRevenue: 3900,
    collectedRevenue: 2925,
    costPerClient: 69.33,
    contractedROI: 1775.0,
    collectedROI: 1306.25,
  },
  {
    date: "2026-02-20",
    adSpend: 220,
    impressions: 19600,
    cpi: 11.22,
    linkClicks: 261,
    ctr: 1.33,
    cpc: 0.84,
    messages: 46,
    costPerMessage: 4.78,    calls60Booked: 5,
    costPer60Booked: 44.0,
    calls60Taken: 4,
    showUp60Pct: 80.0,
    newClients: 3,
    closeRate: 75.0,
    msgConversionRate: 10.87,
    contractedRevenue: 3900,
    collectedRevenue: 2925,
    costPerClient: 73.33,
    contractedROI: 1672.73,
    collectedROI: 1229.55,
  },
  {
    date: "2026-02-21",
    adSpend: 207,
    impressions: 18400,
    cpi: 11.25,
    linkClicks: 245,
    ctr: 1.33,
    cpc: 0.84,
    messages: 49,
    costPerMessage: 4.22,    calls60Booked: 5,
    costPer60Booked: 41.4,
    calls60Taken: 4,
    showUp60Pct: 80.0,
    newClients: 4,
    closeRate: 100.0,
    msgConversionRate: 10.2,
    contractedRevenue: 5200,
    collectedRevenue: 3900,
    costPerClient: 51.75,
    contractedROI: 2411.59,
    collectedROI: 1783.57,
  },
];

// ============================================================================
// 2. monthlyAdsRollup – Aggregated monthly totals (array form)
// ============================================================================

export interface MonthlyAdsRollupEntry {
  month: string;
  adSpend: number;
  impressions: number;
  cpi: number;
  linkClicks: number;
  ctr: number;
  cpc: number;
  messages: number;
  costPerMessage: number;
  calls60Booked: number;
  costPer60Booked: number;
  calls60Taken: number;
  showUp60Pct: number;
  newClients: number;
  closeRate: number;
  msgConversionRate: number;
  contractedRevenue: number;
  collectedRevenue: number;
  costPerClient: number;
  contractedROI: number;
  collectedROI: number;
}

export const monthlyAdsRollupByMonth: MonthlyAdsRollupEntry[] = [
  {
    month: "2026-01",
    adSpend: 3449,
    impressions: 302800,
    cpi: 11.39,
    linkClicks: 4019,
    ctr: 1.33,
    cpc: 0.86,
    messages: 666,
    costPerMessage: 5.18,    calls60Booked: 64,
    costPer60Booked: 53.89,
    calls60Taken: 53,
    showUp60Pct: 82.81,
    newClients: 42,
    closeRate: 79.25,
    msgConversionRate: 9.61,
    contractedRevenue: 52591,
    collectedRevenue: 33441,
    costPerClient: 82.12,
    contractedROI: 1424.62,
    collectedROI: 869.72,
  },
  {
    month: "2026-02",
    adSpend: 3873,
    impressions: 326200,
    cpi: 11.24,
    linkClicks: 4344,
    ctr: 1.33,
    cpc: 0.84,
    messages: 774,
    costPerMessage: 4.84,    calls60Booked: 80,
    costPer60Booked: 48.41,
    calls60Taken: 63,
    showUp60Pct: 78.75,
    newClients: 53,
    closeRate: 84.13,
    msgConversionRate: 10.34,
    contractedRevenue: 69900,
    collectedRevenue: 52835,
    costPerClient: 73.08,
    contractedROI: 1705.19,
    collectedROI: 1264.29,
  },
];

// Legacy object form used by overview page
export const monthlyAdsRollup = {
  totalSpend: 3873,
  totalSpendLastMonth: 3449,
  totalImpressions: 326200,
  totalClicks: 4344,
  totalMessages: 774,
  totalCallsBooked: 99,
  totalClientsClosed: 53,
};

// ============================================================================
// 3. coachingFeedback – Client check-in feedback entries
// ============================================================================

export interface CoachingFeedbackEntry {
  timestamp: string;
  name: string;
  coachRating: number;
  workoutCompletion: "Yes" | "Partial" | "No";
  missedReason: string;
  sleepRating: number;
  nutritionRating: number;
  energyRating: number;
  npsScore: number;
  feedback: string;
  wins: string;
  coachName: string;
  date: string;
}

export const coachingFeedback: CoachingFeedbackEntry[] = [
  {
    timestamp: "2026-02-03T08:15:00Z",
    name: "Marcus Rivera",
    coachRating: 9,
    workoutCompletion: "Yes",
    missedReason: "",
    sleepRating: 8,
    nutritionRating: 7,
    energyRating: 8,
    npsScore: 9,
    feedback:
      "Ignacio keeps me on track. Love the accountability check-ins every morning.",
    wins: "Hit a 315lb squat PR this week!",
    coachName: "Ignacio",
    date: "2026-02-03",
  },
  {
    timestamp: "2026-02-03T10:22:00Z",
    name: "Jasmine Okafor",
    coachRating: 10,
    workoutCompletion: "Yes",
    missedReason: "",
    sleepRating: 9,
    nutritionRating: 9,
    energyRating: 9,
    npsScore: 10,
    feedback:
      "Fatima is incredible. She adjusted my macros for Ramadan prep and I still dropped 2lbs.",
    wins: "Down 8lbs total, fitting into old jeans again.",
    coachName: "Fatima",
    date: "2026-02-03",
  },
  {
    timestamp: "2026-02-04T07:45:00Z",
    name: "Derek Lawson",
    coachRating: 7,
    workoutCompletion: "Partial",
    missedReason: "Work travel, missed 2 sessions",
    sleepRating: 5,
    nutritionRating: 6,
    energyRating: 5,
    npsScore: 7,
    feedback:
      "Waleed is solid but I need more flexibility when I travel for work. Maybe travel-friendly workouts?",
    wins: "Maintained weight even while traveling.",
    coachName: "Waleed",
    date: "2026-02-04",
  },
  {
    timestamp: "2026-02-05T09:30:00Z",
    name: "Angela Chen",
    coachRating: 9,
    workoutCompletion: "Yes",
    missedReason: "",
    sleepRating: 7,
    nutritionRating: 8,
    energyRating: 8,
    npsScore: 9,
    feedback:
      "Mark is really knowledgeable. He helped me fix my hip hinge and my deadlift feels so much better.",
    wins: "No more lower back pain during workouts.",
    coachName: "Stef",
    date: "2026-02-05",
  },
  {
    timestamp: "2026-02-05T14:10:00Z",
    name: "Tyler Brooks",
    coachRating: 8,
    workoutCompletion: "Yes",
    missedReason: "",
    sleepRating: 7,
    nutritionRating: 7,
    energyRating: 7,
    npsScore: 8,
    feedback:
      "Josh pushes me hard but in a good way. I wish the app had better meal tracking integration.",
    wins: "First pull-up in 3 years!",
    coachName: "Farrukh",
    date: "2026-02-05",
  },
  {
    timestamp: "2026-02-07T11:20:00Z",
    name: "Brandon Williams",
    coachRating: 6,
    workoutCompletion: "No",
    missedReason: "Got sick with the flu for the whole week",
    sleepRating: 4,
    nutritionRating: 4,
    energyRating: 3,
    npsScore: 6,
    feedback:
      "I was out sick all week. Ignacio checked in which was nice but I feel behind now.",
    wins: "At least I maintained my hydration goal.",
    coachName: "Ignacio",
    date: "2026-02-07",
  },
  {
    timestamp: "2026-02-08T09:15:00Z",
    name: "Samantha Lee",
    coachRating: 9,
    workoutCompletion: "Yes",
    missedReason: "",
    sleepRating: 8,
    nutritionRating: 8,
    energyRating: 8,
    npsScore: 9,
    feedback:
      "Fatima is so patient. She modified exercises for my bad knee and I can still train hard.",
    wins: "Lost 3 inches off my waist in 6 weeks.",
    coachName: "Fatima",
    date: "2026-02-08",
  },
  {
    timestamp: "2026-02-09T16:30:00Z",
    name: "Carlos Mendez",
    coachRating: 8,
    workoutCompletion: "Yes",
    missedReason: "",
    sleepRating: 6,
    nutritionRating: 7,
    energyRating: 7,
    npsScore: 8,
    feedback:
      "Mark gave me a great deload week. I was feeling burnt out and now I feel refreshed.",
    wins: "Sleep improved after switching to evening workouts.",
    coachName: "Stef",
    date: "2026-02-09",
  },
  {
    timestamp: "2026-02-10T07:50:00Z",
    name: "Rachel Foster",
    coachRating: 10,
    workoutCompletion: "Yes",
    missedReason: "",
    sleepRating: 9,
    nutritionRating: 9,
    energyRating: 10,
    npsScore: 10,
    feedback:
      "Josh is amazing! He created a home workout plan since my gym closed for renovation. Didnt miss a beat.",
    wins: "Visible abs for the first time ever!",
    coachName: "Farrukh",
    date: "2026-02-10",
  },
  {
    timestamp: "2026-02-11T10:00:00Z",
    name: "Michael Thompson",
    coachRating: 7,
    workoutCompletion: "Partial",
    missedReason: "Kids were home from school, hard to find time",
    sleepRating: 5,
    nutritionRating: 6,
    energyRating: 5,
    npsScore: 7,
    feedback:
      "Waleed is good but I need shorter workout options for busy days. 90 minute sessions dont work for me right now.",
    wins: "Still hit 3 out of 5 workouts despite the chaos.",
    coachName: "Waleed",
    date: "2026-02-11",
  },
  {
    timestamp: "2026-02-13T08:40:00Z",
    name: "Kevin Nguyen",
    coachRating: 8,
    workoutCompletion: "Yes",
    missedReason: "",
    sleepRating: 7,
    nutritionRating: 7,
    energyRating: 7,
    npsScore: 8,
    feedback:
      "Ignacio is direct and no-nonsense which I appreciate. Would love more video form checks though.",
    wins: "Lost 5lbs this month while getting stronger.",
    coachName: "Ignacio",
    date: "2026-02-13",
  },
  {
    timestamp: "2026-02-14T12:15:00Z",
    name: "Brittany Moore",
    coachRating: 10,
    workoutCompletion: "Yes",
    missedReason: "",
    sleepRating: 9,
    nutritionRating: 9,
    energyRating: 9,
    npsScore: 10,
    feedback:
      "Fatima understands female physiology. She adjusts my training around my cycle and it makes a huge difference.",
    wins: "Energy is the best it has been in years. People at work are asking what I am doing.",
    coachName: "Fatima",
    date: "2026-02-14",
  },
  {
    timestamp: "2026-02-15T09:00:00Z",
    name: "James Patterson",
    coachRating: 8,
    workoutCompletion: "Partial",
    missedReason: "Tweaked my shoulder, had to skip upper body day",
    sleepRating: 7,
    nutritionRating: 7,
    energyRating: 6,
    npsScore: 8,
    feedback:
      "Mark immediately adjusted my program when I told him about the shoulder. Really responsive.",
    wins: "Lower body is still progressing. Squatted 225 for reps.",
    coachName: "Stef",
    date: "2026-02-15",
  },
  {
    timestamp: "2026-02-16T15:30:00Z",
    name: "Aisha Williams",
    coachRating: 9,
    workoutCompletion: "Yes",
    missedReason: "",
    sleepRating: 8,
    nutritionRating: 8,
    energyRating: 8,
    npsScore: 9,
    feedback:
      "Josh made my nutrition plan way simpler. I was overcomplicating it. Now I actually stick to it.",
    wins: "Dropped a dress size and feel more confident.",
    coachName: "Farrukh",
    date: "2026-02-16",
  },
  {
    timestamp: "2026-02-18T11:00:00Z",
    name: "Olivia Hernandez",
    coachRating: 7,
    workoutCompletion: "Partial",
    missedReason: "Period cramps were too bad on Tuesday",
    sleepRating: 6,
    nutritionRating: 7,
    energyRating: 5,
    npsScore: 7,
    feedback:
      "Waleed could be better about understanding womens health stuff. He just said to push through.",
    wins: "Still got 4 of 5 workouts done and hit my protein goal every day.",
    coachName: "Waleed",
    date: "2026-02-18",
  },
  {
    timestamp: "2026-02-19T09:45:00Z",
    name: "Jordan Taylor",
    coachRating: 9,
    workoutCompletion: "Yes",
    missedReason: "",
    sleepRating: 8,
    nutritionRating: 8,
    energyRating: 8,
    npsScore: 9,
    feedback:
      "Ignacio is the real deal. He actually studies my form videos and gives specific cues. Not generic at all.",
    wins: "Added 20lbs to my bench press in 4 weeks.",
    coachName: "Ignacio",
    date: "2026-02-19",
  },
  {
    timestamp: "2026-02-20T14:20:00Z",
    name: "Natasha Petrov",
    coachRating: 10,
    workoutCompletion: "Yes",
    missedReason: "",
    sleepRating: 9,
    nutritionRating: 9,
    energyRating: 10,
    npsScore: 10,
    feedback:
      "Fatima is not just a coach, she is a mentor. She helped me with mindset around food and it changed everything.",
    wins: "No more binge eating episodes for 3 weeks straight. Feeling free.",
    coachName: "Fatima",
    date: "2026-02-20",
  },
];

// ============================================================================
// 4. onboardingTracker – New client onboarding pipeline
// ============================================================================

export interface OnboardingEntry {
  onboarder: string;
  client: string;
  email: string;
  closer: string;
  amountPaid: number;
  pif: boolean | string;
  rescheduleEmailSent: boolean;
  reminderEmail: boolean;
  reachOutCloser: boolean;
  comments: string;
  status: "pending" | "active" | "ghosted";
}

export const onboardingTracker: OnboardingEntry[] = [
  {
    onboarder: "Nicole",
    client: "Marcus Rivera",
    email: "marcus.r@gmail.com",
    closer: "Jacob Broz",
    amountPaid: 1200,
    pif: true,
    rescheduleEmailSent: false,
    reminderEmail: true,
    reachOutCloser: false,
    comments: "Super motivated, came from Keith's IG. Ready to go.",
    status: "active",
  },
  {
    onboarder: "Nicole",
    client: "Jasmine Okafor",
    email: "jasmine.okafor@yahoo.com",
    closer: "Jacob Broz",
    amountPaid: 997,
    pif: true,
    rescheduleEmailSent: false,
    reminderEmail: true,
    reachOutCloser: false,
    comments: "Wants to focus on body recomp. Very coachable.",
    status: "active",
  },
  {
    onboarder: "Nicole",
    client: "Derek Lawson",
    email: "dlawson.biz@outlook.com",
    closer: "Will",
    amountPaid: 500,
    pif: "3-pay",
    rescheduleEmailSent: true,
    reminderEmail: true,
    reachOutCloser: true,
    comments: "Travels 2 weeks/month. Needs flexible plan. Payment plan.",
    status: "active",
  },
  {
    onboarder: "Nicole",
    client: "Angela Chen",
    email: "angela.chen88@gmail.com",
    closer: "Jacob Broz",
    amountPaid: 1500,
    pif: true,
    rescheduleEmailSent: false,
    reminderEmail: true,
    reachOutCloser: false,
    comments:
      "Former athlete, wants to get back into shape. High expectations.",
    status: "active",
  },
  {
    onboarder: "Nicole",
    client: "Tyler Brooks",
    email: "tbrooks@hotmail.com",
    closer: "Will",
    amountPaid: 997,
    pif: true,
    rescheduleEmailSent: false,
    reminderEmail: true,
    reachOutCloser: false,
    comments: "Referred by a friend. Came through Tyson's content.",
    status: "active",
  },
  {
    onboarder: "Nicole",
    client: "Brandon Williams",
    email: "bwilliams22@gmail.com",
    closer: "Will",
    amountPaid: 400,
    pif: "3-pay",
    rescheduleEmailSent: true,
    reminderEmail: true,
    reachOutCloser: true,
    comments:
      "Got sick first week. Needs re-engagement. Second payment pending.",
    status: "active",
  },
  {
    onboarder: "Nicole",
    client: "Samantha Lee",
    email: "sam.lee.fit@gmail.com",
    closer: "Jacob Broz",
    amountPaid: 1500,
    pif: true,
    rescheduleEmailSent: false,
    reminderEmail: true,
    reachOutCloser: false,
    comments: "Bad knee history. Needs modified lower body work. Very engaged.",
    status: "active",
  },
  {
    onboarder: "Nicole",
    client: "Carlos Mendez",
    email: "carlos.m.fit@outlook.com",
    closer: "Will",
    amountPaid: 997,
    pif: true,
    rescheduleEmailSent: false,
    reminderEmail: true,
    reachOutCloser: false,
    comments: "Stressed from work. Wants training for mental health too.",
    status: "active",
  },
  {
    onboarder: "Nicole",
    client: "Rachel Foster",
    email: "rachelfoster@gmail.com",
    closer: "Jacob Broz",
    amountPaid: 1200,
    pif: true,
    rescheduleEmailSent: false,
    reminderEmail: true,
    reachOutCloser: false,
    comments: "Gym closed for renovation but super committed. Home workouts.",
    status: "active",
  },
  {
    onboarder: "Nicole",
    client: "Michael Thompson",
    email: "mthompson.dad@gmail.com",
    closer: "Will",
    amountPaid: 350,
    pif: "3-pay",
    rescheduleEmailSent: true,
    reminderEmail: true,
    reachOutCloser: false,
    comments: "Father of 3, limited time. Needs 45-min sessions max.",
    status: "active",
  },
  {
    onboarder: "Nicole",
    client: "Kevin Nguyen",
    email: "knguyen.dev@gmail.com",
    closer: "Will",
    amountPaid: 997,
    pif: true,
    rescheduleEmailSent: false,
    reminderEmail: true,
    reachOutCloser: false,
    comments: "Software dev, sits all day. Posture correction + strength.",
    status: "active",
  },
  {
    onboarder: "Nicole",
    client: "Brittany Moore",
    email: "britt.moore@gmail.com",
    closer: "Jacob Broz",
    amountPaid: 1200,
    pif: true,
    rescheduleEmailSent: false,
    reminderEmail: true,
    reachOutCloser: false,
    comments: "Cycle-based training request. Very detail-oriented client.",
    status: "active",
  },
  {
    onboarder: "Nicole",
    client: "James Patterson",
    email: "jpatt.lift@outlook.com",
    closer: "Will",
    amountPaid: 500,
    pif: "3-pay",
    rescheduleEmailSent: false,
    reminderEmail: true,
    reachOutCloser: false,
    comments: "Shoulder issue. Modified upper body plan in place.",
    status: "active",
  },
  {
    onboarder: "Nicole",
    client: "Aisha Williams",
    email: "aisha.w@gmail.com",
    closer: "Jacob Broz",
    amountPaid: 997,
    pif: true,
    rescheduleEmailSent: false,
    reminderEmail: true,
    reachOutCloser: false,
    comments: "Nutrition was her main pain point. Simplified meal plan.",
    status: "active",
  },
  {
    onboarder: "Nicole",
    client: "Daniel Kim",
    email: "dkim.strong@gmail.com",
    closer: "Jacob Broz",
    amountPaid: 1500,
    pif: true,
    rescheduleEmailSent: false,
    reminderEmail: true,
    reachOutCloser: false,
    comments: "Home gym setup. Powerlifting focus. Extremely dedicated.",
    status: "active",
  },
  {
    onboarder: "Nicole",
    client: "Olivia Hernandez",
    email: "olivia.h.fit@yahoo.com",
    closer: "Will",
    amountPaid: 400,
    pif: "3-pay",
    rescheduleEmailSent: true,
    reminderEmail: true,
    reachOutCloser: true,
    comments:
      "Mentioned period issues affecting training. Coach could improve sensitivity here.",
    status: "active",
  },
  {
    onboarder: "Nicole",
    client: "Jordan Taylor",
    email: "jtaylor.iron@gmail.com",
    closer: "Jacob Broz",
    amountPaid: 1200,
    pif: true,
    rescheduleEmailSent: false,
    reminderEmail: true,
    reachOutCloser: false,
    comments: "Wants to compete in a local powerlifting meet in June.",
    status: "active",
  },
  {
    onboarder: "Nicole",
    client: "Natasha Petrov",
    email: "natasha.petrov@gmail.com",
    closer: "Will",
    amountPaid: 1500,
    pif: true,
    rescheduleEmailSent: false,
    reminderEmail: true,
    reachOutCloser: false,
    comments:
      "Dealing with binge eating history. Needs mindset + nutrition coaching.",
    status: "active",
  },
  {
    onboarder: "Nicole",
    client: "Ryan Mitchell",
    email: "rmitchell@protonmail.com",
    closer: "Will",
    amountPaid: 0,
    pif: false,
    rescheduleEmailSent: true,
    reminderEmail: true,
    reachOutCloser: true,
    comments: "No-showed onboarding call twice. Closer following up.",
    status: "ghosted",
  },
  {
    onboarder: "Nicole",
    client: "Elena Vasquez",
    email: "elena.v.coaching@gmail.com",
    closer: "Jacob Broz",
    amountPaid: 0,
    pif: false,
    rescheduleEmailSent: true,
    reminderEmail: true,
    reachOutCloser: true,
    comments:
      "Said she needs to think about it. Follow-up in 3 days. Warm lead.",
    status: "pending",
  },
  {
    onboarder: "Nicole",
    client: "Trevor Adams",
    email: "trevor.adams@gmail.com",
    closer: "Will",
    amountPaid: 0,
    pif: false,
    rescheduleEmailSent: true,
    reminderEmail: true,
    reachOutCloser: true,
    comments: "Went dark after initial call. Sent 3 follow-ups.",
    status: "ghosted",
  },
  {
    onboarder: "Nicole",
    client: "Lisa Park",
    email: "lisa.park.nyc@gmail.com",
    closer: "Jacob Broz",
    amountPaid: 0,
    pif: false,
    rescheduleEmailSent: false,
    reminderEmail: true,
    reachOutCloser: false,
    comments: "Booked onboarding for Feb 23. Waiting.",
    status: "pending",
  },
];

// ============================================================================
// 5. salesData – Sales pipeline summary
// ============================================================================

export interface CloserStat {
  name: string;
  callsBooked: number;
  callsTaken: number;
  closed: number;
  revenue: number;
}

export interface SalesData {
  totalCallsBooked: number;
  liveCallsCompleted: number;
  totalWon: number;
  totalLost: number;
  revenueTotal: number;
  totalCash: number;
  cashOnCalls: number;
  subscriptions: number;
  closerStats: CloserStat[];
}

export const salesData: SalesData = {
  totalCallsBooked: 188,
  liveCallsCompleted: 149,
  totalWon: 95,
  totalLost: 54,
  revenueTotal: 122491,
  totalCash: 86276,
  cashOnCalls: 72435,
  subscriptions: 13841,
  closerStats: [
    {
      name: "Jacob Broz",
      callsBooked: 108,
      callsTaken: 88,
      closed: 58,
      revenue: 74520,
    },
    {
      name: "Will",
      callsBooked: 80,
      callsTaken: 61,
      closed: 37,
      revenue: 47971,
    },
  ],
};

// ============================================================================
// 6. coachPerformance – Individual coach metrics
// ============================================================================

export interface CoachPerformanceEntry {
  name: string;
  activeClients: number;
  avgRating: number;
  avgNPS: number;
  completionRate: number;
  source: "keith" | "tyson";
}

export const coachPerformance: CoachPerformanceEntry[] = [
  {
    name: "Ignacio",
    activeClients: 18,
    avgRating: 8.5,
    avgNPS: 8.8,
    completionRate: 88,
    source: "keith",
  },
  {
    name: "Fatima",
    activeClients: 16,
    avgRating: 9.8,
    avgNPS: 9.8,
    completionRate: 96,
    source: "keith",
  },
  {
    name: "Waleed",
    activeClients: 14,
    avgRating: 7.0,
    avgNPS: 7.0,
    completionRate: 72,
    source: "tyson",
  },
  {
    name: "Stef",
    activeClients: 15,
    avgRating: 8.3,
    avgNPS: 8.3,
    completionRate: 85,
    source: "tyson",
  },
  {
    name: "Farrukh",
    activeClients: 15,
    avgRating: 8.8,
    avgNPS: 8.8,
    completionRate: 90,
    source: "keith",
  },
];

// ============================================================================
// 7. revenueByMonth – Monthly revenue split by influencer source (for charts)
// ============================================================================

export interface RevenueByMonthEntry {
  month: string;
  keith: number;
  tyson: number;
  total: number;
}

export const revenueByMonth: RevenueByMonthEntry[] = [
  { month: "2025-09", keith: 8200, tyson: 5100, total: 13300 },
  { month: "2025-10", keith: 12400, tyson: 8900, total: 21300 },
  { month: "2025-11", keith: 16800, tyson: 12200, total: 29000 },
  { month: "2025-12", keith: 19500, tyson: 15800, total: 35300 },
  { month: "2026-01", keith: 28600, tyson: 23991, total: 52591 },
  { month: "2026-02", keith: 38200, tyson: 31700, total: 69900 },
];

// ============================================================================
// 8. businessHealth – Overall business health score & insights
// ============================================================================

export interface BusinessHealth {
  score: number;
  constraints: string[];
  opportunities: string[];
}

export const businessHealth: BusinessHealth = {
  score: 82,
  constraints: [
    "Waleed's completion rate (72%) and NPS (7.0) are significantly below team average - risk of client churn on his roster",
    "Show-up rate for 60-min calls dropped to 78.75% in Feb - lost revenue from no-shows",
    "4 clients on payment plans have outstanding balances totaling $2,450",
    "Coach capacity nearing limit - Ignacio (18) and Josh (15) approaching max load of 20 clients each",
    "Collected revenue lags contracted by ~24% indicating cash flow timing gap",
  ],
  opportunities: [
    "February ROI hit 1364% - strong signal to increase ad spend by 30-50% while maintaining efficiency",
    "Fatima's 9.8 avg rating and 96% completion rate make her ideal for high-ticket premium tier",
    "Keith's funnel produces 55% of revenue - test scaling his content budget separately",
    "Message-to-client conversion improved from 9.6% to 10.3% month-over-month - DM script is working",
    "Adding 2 more coaches would unlock capacity for ~40 additional clients at current close rates",
    "Tyson's audience is catching up - his revenue share grew from 45% to 46% in Feb suggesting untapped potential",
    "Implement automated no-show recovery sequence to recapture the 21% of missed 60-min calls",
    "Launch referral program - multiple clients mentioning friends and coworkers asking about their results",
  ],
};

// ============================================================================
// Changelog – business changes with before/after metrics
// ============================================================================

export interface ChangelogEntry {
  id: string;
  date: string;
  category: 'ad_creative' | 'dm_script' | 'pricing' | 'team' | 'process' | 'offer';
  description: string;
  metricBefore: { label: string; value: string };
  metricAfter: { label: string; value: string } | null;
  impactDollars: number | null;
  impactLabel: string | null;
  addedBy: string;
  measurementDays: number;
}

export const changelog: ChangelogEntry[] = [
  {
    id: 'cl-1',
    date: '2026-02-18',
    category: 'dm_script',
    description: 'Updated DM opener from question format to testimonial-first approach',
    metricBefore: { label: 'Message-to-Call Rate', value: '9.6%' },
    metricAfter: { label: 'Message-to-Call Rate', value: '10.3%' },
    impactDollars: 4100,
    impactLabel: '+$4,100/mo projected',
    addedBy: 'Alex',
    measurementDays: 7,
  },
  {
    id: 'cl-2',
    date: '2026-02-14',
    category: 'ad_creative',
    description: 'Launched Keith video #3 with gym b-roll and client transformation clips',
    metricBefore: { label: 'CTR', value: '1.31%' },
    metricAfter: { label: 'CTR', value: '1.35%' },
    impactDollars: 1800,
    impactLabel: '+$1,800/mo from higher CTR',
    addedBy: 'Alex',
    measurementDays: 14,
  },
  {
    id: 'cl-3',
    date: '2026-02-10',
    category: 'team',
    description: 'Started Waleed on new client communication protocol — daily check-in texts + weekly video calls',
    metricBefore: { label: 'Waleed Avg Rating', value: '7.0/10' },
    metricAfter: null,
    impactDollars: null,
    impactLabel: 'Measuring... (7 day window)',
    addedBy: 'Alex',
    measurementDays: 14,
  },
  {
    id: 'cl-4',
    date: '2026-02-05',
    category: 'process',
    description: 'Added automated SMS reminder 2 hours before 60-min calls',
    metricBefore: { label: '60-min Show-up Rate', value: '76.2%' },
    metricAfter: { label: '60-min Show-up Rate', value: '78.8%' },
    impactDollars: 2800,
    impactLabel: '+$2,800/mo from recovered no-shows',
    addedBy: 'Alex',
    measurementDays: 14,
  },
  {
    id: 'cl-5',
    date: '2026-01-28',
    category: 'pricing',
    description: 'Introduced 3-pay option alongside PIF — $1,100 PIF or 3x $450',
    metricBefore: { label: 'Close Rate', value: '29.8%' },
    metricAfter: { label: 'Close Rate', value: '33.3%' },
    impactDollars: 7200,
    impactLabel: '+$7,200/mo from higher close rate',
    addedBy: 'Alex',
    measurementDays: 21,
  },
  {
    id: 'cl-6',
    date: '2026-01-20',
    category: 'offer',
    description: 'Added free meal plan PDF as lead magnet for DM conversations',
    metricBefore: { label: 'DM Response Rate', value: '34%' },
    metricAfter: { label: 'DM Response Rate', value: '41%' },
    impactDollars: 3500,
    impactLabel: '+$3,500/mo from more engaged leads',
    addedBy: 'Alex',
    measurementDays: 14,
  },
  {
    id: 'cl-7',
    date: '2026-01-15',
    category: 'ad_creative',
    description: 'Split-tested Tyson story ad vs static image — story format won',
    metricBefore: { label: 'Tyson CPM', value: '$4.12' },
    metricAfter: { label: 'Tyson CPM', value: '$3.78' },
    impactDollars: 1200,
    impactLabel: '+$1,200/mo from lower ad costs',
    addedBy: 'Alex',
    measurementDays: 14,
  },
  {
    id: 'cl-8',
    date: '2026-01-08',
    category: 'process',
    description: 'Implemented 48-hour onboarding kickoff call requirement for new clients',
    metricBefore: { label: 'Ghost Rate', value: '12%' },
    metricAfter: { label: 'Ghost Rate', value: '8.3%' },
    impactDollars: 4400,
    impactLabel: '+$4,400/mo from retained onboards',
    addedBy: 'Alex',
    measurementDays: 30,
  },
];

// ============================================================================
// 10. setterStats – Setter (DM handler) performance
// ============================================================================

export interface SetterStat {
  name: string;
  messagesHandled: number;
  callsBooked: number;
  conversionRate: number;
  source: "keith" | "tyson";
}

export const setterStats: SetterStat[] = [
  {
    name: "Nicole",
    messagesHandled: 420,
    callsBooked: 54,
    conversionRate: 12.9,
    source: "keith",
  },
  {
    name: "Jared",
    messagesHandled: 354,
    callsBooked: 45,
    conversionRate: 12.7,
    source: "tyson",
  },
];

// ============================================================================
// 11. teamMembers – All team members
// ============================================================================

export interface TeamMember {
  name: string;
  role: string;
  email: string;
  status: "active" | "inactive";
  source?: "keith" | "tyson" | "both";
}

export const teamMembers: TeamMember[] = [
  { name: "Alex Walsh", role: "CEO / Ads", email: "alexwalsh520@gmail.com", status: "active", source: "both" },
  { name: "Matt", role: "Sales Manager", email: "matthew@clientconversion.io", status: "active", source: "both" },
  { name: "Ignacio", role: "Coach", email: "ignacio@clientconversion.io", status: "active", source: "keith" },
  { name: "Nicole", role: "Onboarding Specialist", email: "nicole@clientconversion.io", status: "active", source: "both" },
  { name: "Jacob Broz", role: "Closer", email: "jacob@clientconversion.io", status: "active", source: "both" },
  { name: "Will", role: "Closer", email: "will@clientconversion.io", status: "active", source: "both" },
  { name: "Omar", role: "DM Setter", email: "omar@clientconversion.io", status: "active", source: "keith" },
  { name: "Lina", role: "DM Setter", email: "lina@clientconversion.io", status: "active", source: "keith" },
  { name: "Samir", role: "DM Setter", email: "samir@clientconversion.io", status: "active", source: "tyson" },
  { name: "Dana", role: "DM Setter", email: "dana@clientconversion.io", status: "active", source: "tyson" },
  { name: "Fatima", role: "Coach", email: "fatima@clientconversion.io", status: "active", source: "keith" },
  { name: "Waleed", role: "Coach", email: "waleed@clientconversion.io", status: "active", source: "tyson" },
  { name: "Stef", role: "Coach", email: "stef@clientconversion.io", status: "active", source: "tyson" },
  { name: "Farrukh", role: "Coach", email: "farrukh@clientconversion.io", status: "active", source: "keith" },
];

// ============================================================================
// 12. eodReports – End-of-day reports from team members
// ============================================================================

export interface EODReport {
  id: string;
  date: string;
  submittedBy: string;
  role: "closer" | "coach";
  reportsTo: string;
  callsTaken?: number;
  callsClosed?: number;
  revenue?: number;
  clientsCheckedIn?: number;
  workoutsReviewed?: number;
  issuesFlagged?: number;
  testimonialsCollected?: number;
  challenges: string;
  wins: string;
  notes: string;
}

export const eodReports: EODReport[] = [
  {
    id: "eod-1",
    date: "2026-02-21",
    submittedBy: "Jacob Broz",
    role: "closer",
    reportsTo: "Matt",
    callsTaken: 6,
    callsClosed: 4,
    revenue: 5200,
    challenges: "Two no-shows in the afternoon block",
    wins: "Closed a PIF at $1,500 — client was super motivated from Keith's latest reel",
    notes: "Need to follow up with Derek L. tomorrow, he asked for 24hrs to think",
  },
  {
    id: "eod-2",
    date: "2026-02-21",
    submittedBy: "Will",
    role: "closer",
    reportsTo: "Matt",
    callsTaken: 5,
    callsClosed: 3,
    revenue: 3600,
    challenges: "One call went 90 mins, prospect had a lot of objections about pricing",
    wins: "Converted a Tyson lead who had been on the fence for 2 weeks",
    notes: "Thinking we should test a new close for the price objection — will discuss with Matt",
  },
  {
    id: "eod-3",
    date: "2026-02-21",
    submittedBy: "Ignacio",
    role: "coach",
    reportsTo: "Ignacio",
    clientsCheckedIn: 16,
    workoutsReviewed: 14,
    issuesFlagged: 1,
    testimonialsCollected: 1,
    challenges: "Brandon W. missed check-in again — might need escalation",
    wins: "Marcus R. hit a squat PR, got a video testimonial from him",
    notes: "Running weekly standup tomorrow at 10am",
  },
  {
    id: "eod-4",
    date: "2026-02-21",
    submittedBy: "Fatima",
    role: "coach",
    reportsTo: "Ignacio",
    clientsCheckedIn: 15,
    workoutsReviewed: 15,
    issuesFlagged: 0,
    testimonialsCollected: 0,
    challenges: "Nothing major today, all clients on track",
    wins: "Samantha L. lost 3 inches off her waist — incredible progress",
    notes: "Jasmine is doing amazing on her Ramadan-adjusted plan",
  },
  {
    id: "eod-5",
    date: "2026-02-20",
    submittedBy: "Jacob Broz",
    role: "closer",
    reportsTo: "Matt",
    callsTaken: 7,
    callsClosed: 5,
    revenue: 6100,
    challenges: "Morning slot was packed, barely had breaks between calls",
    wins: "Best day this week — 5 closes including two PIFs",
    notes: "The new testimonial-first opener Matt suggested is working really well",
  },
  {
    id: "eod-6",
    date: "2026-02-20",
    submittedBy: "Waleed",
    role: "coach",
    reportsTo: "Ignacio",
    clientsCheckedIn: 12,
    workoutsReviewed: 10,
    issuesFlagged: 2,
    testimonialsCollected: 0,
    challenges: "Michael T. needs shorter workouts. Derek L. missed another check-in.",
    wins: "Got positive feedback from 3 clients on the new programming style",
    notes: "Working on creating 45-min express versions of all programs",
  },
];

// ============================================================================
// COACHING HUB – Extended mock data for new tables
// ============================================================================

import type {
  Client,
  CoachMilestone,
  ProgramPause,
  CoachMeeting,
  CoachEODReport,
  EODClientCheckin,
  FinanceRecord,
} from "./types";

export const mockClients: Client[] = [
  { id: 1, name: "Marcus Rivera", email: "marcus.r@gmail.com", coachName: "Ignacio", program: "12-Week Transform", offer: "Keith Standard", startDate: "2026-01-06", endDate: "2026-03-30", status: "active", paymentPlatform: "Stripe", salesFathomLink: "https://fathom.video/share/example1", onboardingFathomLink: "https://fathom.video/share/ob-example1", salesPerson: "", comments: "", onboardingDate: null, onboardingStatus: null, amountPaid: 1200 },
  { id: 2, name: "Jasmine Okafor", email: "jasmine.o@gmail.com", coachName: "Fatima", program: "12-Week Transform", offer: "Keith Premium", startDate: "2026-01-13", endDate: "2026-04-06", status: "active", paymentPlatform: "Stripe", salesFathomLink: "https://fathom.video/share/example2", onboardingFathomLink: "https://fathom.video/share/ob-example2", salesPerson: "", comments: "", onboardingDate: null, onboardingStatus: null, amountPaid: 1800 },
  { id: 3, name: "Derek Lawson", email: "derek.l@gmail.com", coachName: "Waleed", program: "8-Week Kickstart", offer: "Tyson Standard", startDate: "2026-01-20", endDate: "2026-03-16", status: "active", paymentPlatform: "Stripe", salesFathomLink: "", onboardingFathomLink: "", salesPerson: "", comments: "", onboardingDate: null, onboardingStatus: null, amountPaid: 900 },
  { id: 4, name: "Angela Chen", email: "angela.c@gmail.com", coachName: "Stef", program: "12-Week Transform", offer: "Tyson Premium", startDate: "2026-02-03", endDate: "2026-04-27", status: "active", paymentPlatform: "Stripe", salesFathomLink: "https://fathom.video/share/example4", onboardingFathomLink: "https://fathom.video/share/ob-example4", salesPerson: "", comments: "", onboardingDate: null, onboardingStatus: null, amountPaid: 1500 },
  { id: 5, name: "Rachel Foster", email: "rachel.f@gmail.com", coachName: "Farrukh", program: "12-Week Transform", offer: "Keith Standard", startDate: "2025-12-15", endDate: "2026-03-09", status: "active", paymentPlatform: "Stripe", salesFathomLink: "", onboardingFathomLink: "https://fathom.video/share/ob-example5", salesPerson: "", comments: "", onboardingDate: null, onboardingStatus: null, amountPaid: 1200 },
  { id: 6, name: "Brandon Williams", email: "brandon.w@gmail.com", coachName: "Ignacio", program: "8-Week Kickstart", offer: "Keith Standard", startDate: "2026-02-10", endDate: "2026-04-06", status: "active", paymentPlatform: "Stripe", salesFathomLink: "", onboardingFathomLink: "", salesPerson: "", comments: "", onboardingDate: null, onboardingStatus: null, amountPaid: 900 },
  { id: 7, name: "Samantha Lee", email: "samantha.l@gmail.com", coachName: "Fatima", program: "12-Week Transform", offer: "Tyson Standard", startDate: "2026-01-06", endDate: "2026-03-30", status: "active", paymentPlatform: "Stripe", salesFathomLink: "https://fathom.video/share/example7", onboardingFathomLink: "https://fathom.video/share/ob-example7", salesPerson: "", comments: "", onboardingDate: null, onboardingStatus: null, amountPaid: 1200 },
  { id: 8, name: "Michael Torres", email: "michael.t@gmail.com", coachName: "Waleed", program: "8-Week Kickstart", offer: "Tyson Standard", startDate: "2026-02-17", endDate: "2026-04-13", status: "active", paymentPlatform: "Stripe", salesFathomLink: "", onboardingFathomLink: "", salesPerson: "", comments: "", onboardingDate: null, onboardingStatus: null, amountPaid: 900 },
  { id: 9, name: "Nathan Price", email: "nathan.p@gmail.com", coachName: "Ignacio", program: "12-Week Transform", offer: "Keith Premium", startDate: "2026-02-24", endDate: "2026-05-18", status: "active", paymentPlatform: "Stripe", salesFathomLink: "", onboardingFathomLink: "", salesPerson: "", comments: "", onboardingDate: null, onboardingStatus: null, amountPaid: 1800 },
  { id: 10, name: "Michael Blake", email: "michael.b@gmail.com", coachName: "Stef", program: "12-Week Transform", offer: "Tyson Standard", startDate: "2026-01-13", endDate: "2026-04-06", status: "refunded", paymentPlatform: "Stripe", salesFathomLink: "", onboardingFathomLink: "", salesPerson: "", comments: "", onboardingDate: null, onboardingStatus: null, amountPaid: 1820 },
  { id: 11, name: "Jakob Padgett", email: "jakob.p@gmail.com", coachName: "Ignacio", program: "12-Week Transform", offer: "Keith Standard", startDate: "2026-03-16", endDate: "2026-06-08", status: "active", paymentPlatform: "Stripe", salesFathomLink: "", onboardingFathomLink: "https://fathom.video/share/jmxkzT_y-getpn7jrsFZuT5LA1kmNxsq", salesPerson: "", comments: "", onboardingDate: null, onboardingStatus: null, amountPaid: 1200 },
  { id: 12, name: "Ethan Escobedo", email: "ethan.e@gmail.com", coachName: "Farrukh", program: "8-Week Kickstart", offer: "Keith Standard", startDate: "2026-03-16", endDate: "2026-05-11", status: "active", paymentPlatform: "Stripe", salesFathomLink: "", onboardingFathomLink: "https://fathom.video/share/UH95QNKddAKs7EGz7ZTDHK4LTdx7nve-", salesPerson: "", comments: "", onboardingDate: null, onboardingStatus: null, amountPaid: 900 },
  { id: 13, name: "Hunter Olsen", email: "hunter.o@gmail.com", coachName: "Waleed", program: "12-Week Transform", offer: "Tyson Standard", startDate: "2026-02-10", endDate: "2026-05-04", status: "cancelled", paymentPlatform: "Stripe", salesFathomLink: "", onboardingFathomLink: "", salesPerson: "", comments: "", onboardingDate: null, onboardingStatus: null, amountPaid: 1200 },
  { id: 14, name: "Matthew Ryan", email: "matthew.r@gmail.com", coachName: "Ignacio", program: "8-Week Kickstart", offer: "Keith Standard", startDate: "2026-03-03", endDate: "2026-04-28", status: "active", paymentPlatform: "Stripe", salesFathomLink: "", onboardingFathomLink: "", salesPerson: "", comments: "", onboardingDate: null, onboardingStatus: null, amountPaid: 900 },
  { id: 15, name: "Ryan Cooper", email: "ryan.c@gmail.com", coachName: "Ignacio", program: "12-Week Transform", offer: "Tyson Premium", startDate: "2026-03-10", endDate: "2026-06-01", status: "active", paymentPlatform: "Stripe", salesFathomLink: "", onboardingFathomLink: "", salesPerson: "", comments: "", onboardingDate: null, onboardingStatus: null, amountPaid: 1500 },
];

export const mockMilestones: CoachMilestone[] = [
  { id: 1, clientId: 1, clientName: "Marcus Rivera", coachName: "Ignacio", trustPilotPromptedDate: "2026-01-20", trustPilotCompleted: true, trustPilotCompletionDate: "2026-01-22", videoTestimonialPromptedDate: "2026-03-23", videoTestimonialCompleted: false, videoTestimonialCompletionDate: null, retentionPromptedDate: "2026-03-09", retentionCompleted: false, retentionCompletionDate: null, referralPromptedDate: "2026-03-23", referralCompleted: false, referralCompletionDate: null },
  { id: 2, clientId: 2, clientName: "Jasmine Okafor", coachName: "Fatima", trustPilotPromptedDate: "2026-01-27", trustPilotCompleted: true, trustPilotCompletionDate: "2026-01-28", videoTestimonialPromptedDate: null, videoTestimonialCompleted: false, videoTestimonialCompletionDate: null, retentionPromptedDate: "2026-03-16", retentionCompleted: false, retentionCompletionDate: null, referralPromptedDate: null, referralCompleted: false, referralCompletionDate: null },
  { id: 3, clientId: 3, clientName: "Derek Lawson", coachName: "Waleed", trustPilotPromptedDate: "2026-02-03", trustPilotCompleted: false, trustPilotCompletionDate: null, videoTestimonialPromptedDate: null, videoTestimonialCompleted: false, videoTestimonialCompletionDate: null, retentionPromptedDate: null, retentionCompleted: false, retentionCompletionDate: null, referralPromptedDate: null, referralCompleted: false, referralCompletionDate: null },
  { id: 4, clientId: 4, clientName: "Angela Chen", coachName: "Stef", trustPilotPromptedDate: "2026-02-17", trustPilotCompleted: true, trustPilotCompletionDate: "2026-02-19", videoTestimonialPromptedDate: null, videoTestimonialCompleted: false, videoTestimonialCompletionDate: null, retentionPromptedDate: null, retentionCompleted: false, retentionCompletionDate: null, referralPromptedDate: null, referralCompleted: false, referralCompletionDate: null },
  { id: 5, clientId: 5, clientName: "Rachel Foster", coachName: "Farrukh", trustPilotPromptedDate: "2025-12-29", trustPilotCompleted: true, trustPilotCompletionDate: "2025-12-30", videoTestimonialPromptedDate: "2026-03-02", videoTestimonialCompleted: true, videoTestimonialCompletionDate: "2026-03-04", retentionPromptedDate: "2026-02-16", retentionCompleted: true, retentionCompletionDate: "2026-02-20", referralPromptedDate: "2026-03-02", referralCompleted: false, referralCompletionDate: null },
  { id: 6, clientId: 7, clientName: "Samantha Lee", coachName: "Fatima", trustPilotPromptedDate: "2026-01-20", trustPilotCompleted: true, trustPilotCompletionDate: "2026-01-21", videoTestimonialPromptedDate: "2026-03-23", videoTestimonialCompleted: false, videoTestimonialCompletionDate: null, retentionPromptedDate: "2026-03-09", retentionCompleted: false, retentionCompletionDate: null, referralPromptedDate: null, referralCompleted: false, referralCompletionDate: null },
];

export const mockPauses: ProgramPause[] = [
  { id: 1, clientId: 3, clientName: "Derek Lawson", coachName: "Waleed", pauseStartDate: "2026-02-20", pauseDays: 7, reason: "Work travel - overseas conference", approved: true },
  { id: 2, clientId: 8, clientName: "Michael Torres", coachName: "Waleed", pauseStartDate: "2026-03-10", pauseDays: 5, reason: "Family emergency", approved: true },
];

export const mockMeetings: CoachMeeting[] = [
  { id: 1, clientId: 1, clientName: "Marcus Rivera", coachName: "Ignacio", meetingDate: "2026-03-15", durationMinutes: 30, notes: "Reviewed squat form. Set new PR goal of 335lb by end of program. Client highly motivated." },
  { id: 2, clientId: 2, clientName: "Jasmine Okafor", coachName: "Fatima", meetingDate: "2026-03-14", durationMinutes: 25, notes: "Discussed Ramadan nutrition plan. Adjusted macros to maintain energy. Client very happy with progress." },
  { id: 3, clientId: 4, clientName: "Angela Chen", coachName: "Stef", meetingDate: "2026-03-13", durationMinutes: 20, notes: "Fixed hip hinge form on deadlifts. Added mobility warm-up routine. Client feeling much better." },
  { id: 4, clientId: 5, clientName: "Rachel Foster", coachName: "Farrukh", meetingDate: "2026-03-12", durationMinutes: 35, notes: "Home workout plan review. Added resistance band exercises. Discussed retention — client interested in continuing." },
  { id: 5, clientId: 7, clientName: "Samantha Lee", coachName: "Fatima", meetingDate: "2026-03-11", durationMinutes: 30, notes: "3-inch waist reduction celebration! Adjusted training split for next phase. Talked about referral program." },
  { id: 6, clientId: 6, clientName: "Brandon Williams", coachName: "Ignacio", meetingDate: "2026-03-10", durationMinutes: 20, notes: "Client has been quiet. Discussed commitment and set daily check-in routine. Will monitor closely." },
  { id: 7, clientId: 9, clientName: "Nathan Price", coachName: "Ignacio", meetingDate: "2026-03-16", durationMinutes: 25, notes: "Initial assessment call. Set up nutrition forms. Client eager to start." },
  { id: 8, clientId: 11, clientName: "Jakob Padgett", coachName: "Ignacio", meetingDate: "2026-03-17", durationMinutes: 30, notes: "New client intro call. Went over program expectations and app walkthrough. Sent first week plan." },
];

export const mockEODReports: CoachEODReport[] = [
  {
    id: 1, submittedBy: "Stef Hughes", role: "coach", date: "2026-03-16",
    activeClientCount: 8, newClients: 1, newClientNames: ["Jakob Padgett"], accountsDeactivated: 0, deactivatedClientNames: [],
    communityEngagement: "Reading through community groups and reacting to posts on Everfit and Slack. Commented on Nicole's post on Everfit forum.",
    summary: "Sent messages to all clients; Matthew and Ryan have been quiet, but sent them each a message. Sent introduction message to Jakob. Waiting for Jakob to respond. Nathan needs to fill out nutrition forms (reminded him). Marcus came back, said he will give a TP review.",
    questionsForManagement: "Nothing today",
    hoursLogged: 6, feelingToday: "Feeling good overall; trying not to stress about the 2 not responding",
    clientCheckins: [
      { id: 1, eodId: 1, clientName: "Marcus Rivera", checkedIn: true, notes: "Said he will give TP review" },
      { id: 2, eodId: 1, clientName: "Jakob Padgett", checkedIn: true, notes: "Sent intro message, waiting for response" },
      { id: 3, eodId: 1, clientName: "Nathan Price", checkedIn: true, notes: "Needs to fill out nutrition forms" },
      { id: 4, eodId: 1, clientName: "Matthew Ryan", checkedIn: false, notes: "Been quiet, sent message" },
      { id: 5, eodId: 1, clientName: "Ryan Cooper", checkedIn: false, notes: "Been quiet, sent message" },
      { id: 6, eodId: 1, clientName: "Brandon Williams", checkedIn: true, notes: "" },
      { id: 7, eodId: 1, clientName: "Samantha Lee", checkedIn: true, notes: "" },
      { id: 8, eodId: 1, clientName: "Rachel Foster", checkedIn: true, notes: "" },
    ],
  },
  {
    id: 2, submittedBy: "Nicole", role: "onboarding", date: "2026-03-16",
    activeClientCount: 0, newClients: 2, newClientNames: ["Jakob Padgett", "Ethan Escobedo"], accountsDeactivated: 0, deactivatedClientNames: [],
    communityEngagement: "",
    summary: "Onboarded Jakob Padgett and Ethan Escobedo. Michael Blake refunded ($1820). Hunter Olsen cancelled. Updated refunds/cancellation tracker, sales info added to client tracker, nutrition info copied, GHL conversations checked, Skool summary done.",
    questionsForManagement: "",
    hoursLogged: 7, feelingToday: "I feel fine",
  },
  {
    id: 3, submittedBy: "Ignacio", role: "coach", date: "2026-03-16",
    activeClientCount: 18, newClients: 0, newClientNames: [], accountsDeactivated: 0, deactivatedClientNames: [],
    communityEngagement: "Posted workout tip in Everfit community. Replied to 5 client posts.",
    summary: "All clients checked in. Marcus hit a PR this week — great progress. Brandon W still needs monitoring. Team standup went well.",
    questionsForManagement: "Can we discuss Waleed's client load at next meeting?",
    hoursLogged: 8, feelingToday: "Productive day, feeling strong about the team",
    clientCheckins: [
      { id: 9, eodId: 3, clientName: "Marcus Rivera", checkedIn: true, notes: "PR this week!" },
      { id: 10, eodId: 3, clientName: "Brandon Williams", checkedIn: true, notes: "Still needs monitoring" },
      { id: 11, eodId: 3, clientName: "Nathan Price", checkedIn: true, notes: "New, getting started" },
      { id: 12, eodId: 3, clientName: "Jakob Padgett", checkedIn: true, notes: "Just onboarded" },
    ],
  },
];

export const mockFinances: FinanceRecord[] = [
  { id: 1, clientId: 1, clientName: "Marcus Rivera", coachName: "Ignacio", amountPaid: 1200, refundAmount: 0, refundReason: "", refundDate: null, retentionRevenue: 0, retentionDate: null },
  { id: 2, clientId: 2, clientName: "Jasmine Okafor", coachName: "Fatima", amountPaid: 1800, refundAmount: 0, refundReason: "", refundDate: null, retentionRevenue: 0, retentionDate: null },
  { id: 3, clientId: 5, clientName: "Rachel Foster", coachName: "Farrukh", amountPaid: 1200, refundAmount: 0, refundReason: "", refundDate: null, retentionRevenue: 1200, retentionDate: "2026-02-20" },
  { id: 4, clientId: 10, clientName: "Michael Blake", coachName: "Stef", amountPaid: 1820, refundAmount: 1820, refundReason: "Client requested full refund — not satisfied with results", refundDate: "2026-03-16", retentionRevenue: 0, retentionDate: null },
  { id: 5, clientId: 13, clientName: "Hunter Olsen", coachName: "Waleed", amountPaid: 1200, refundAmount: 0, refundReason: "", refundDate: null, retentionRevenue: 0, retentionDate: null },
  { id: 6, clientId: 4, clientName: "Angela Chen", coachName: "Stef", amountPaid: 1500, refundAmount: 0, refundReason: "", refundDate: null, retentionRevenue: 0, retentionDate: null },
  { id: 7, clientId: 7, clientName: "Samantha Lee", coachName: "Fatima", amountPaid: 1200, refundAmount: 0, refundReason: "", refundDate: null, retentionRevenue: 0, retentionDate: null },
  { id: 8, clientId: 11, clientName: "Jakob Padgett", coachName: "Ignacio", amountPaid: 1200, refundAmount: 0, refundReason: "", refundDate: null, retentionRevenue: 0, retentionDate: null },
  { id: 9, clientId: 12, clientName: "Ethan Escobedo", coachName: "Farrukh", amountPaid: 900, refundAmount: 0, refundReason: "", refundDate: null, retentionRevenue: 0, retentionDate: null },
];
