/**
 * Public client video-testimonial recording page at
 * /testimonials/record/<token>.
 *
 * Opened by a client on their phone via an unguessable token link generated by
 * their coach in the Milestones tab. No CCOS login (see Sidebar.tsx and
 * AccessGate.tsx public-route exceptions). Shows the guide + a native-camera
 * recorder. The actual upload/submit happens client-side via the token-
 * validated /api/testimonials/video/* endpoints.
 */

import type { Metadata } from "next";
import { getServiceSupabase } from "@/lib/supabase";
import { TESTIMONIAL_GUIDE } from "@/lib/testimonials/video";
import RecordTestimonial from "@/components/testimonials/RecordTestimonial";

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Share your testimonial",
  robots: { index: false, follow: false, nocache: true },
};

export default async function RecordTestimonialPage({
  params,
}: {
  params: Promise<{ token: string }>;
}) {
  const { token } = await params;

  let clientName = "";
  let status: string | null = null;

  try {
    const db = getServiceSupabase();
    const { data } = await db
      .from("video_testimonials")
      .select("client_name, status")
      .eq("token", token)
      .maybeSingle();
    if (data) {
      clientName = data.client_name || "";
      status = data.status;
    }
  } catch {
    // fall through to invalid state
  }

  const firstName = clientName.trim().split(/\s+/)[0] || "there";

  return (
    <RecordTestimonial
      token={token}
      firstName={firstName}
      guide={TESTIMONIAL_GUIDE}
      initialState={status === "submitted" ? "done" : status === "requested" ? "ready" : "invalid"}
    />
  );
}
