import { createHash } from "node:crypto";
import { auth } from "@/auth";
import { getServiceSupabase } from "@/lib/supabase";
import { hasInboxAccess } from "@/lib/inbox/access";
import { requireSameOrigin,HttpError } from "@/lib/everfit/server";
import { parseReport } from "@/lib/everfit-v2/report";
export const dynamic="force-dynamic";
async function access(){const s=await auth();if(!s?.user?.email)throw new HttpError("Please sign in.",401);if(!hasInboxAccess(s.user))throw new HttpError("Coaching access required.",403);return s.user;}
function fail(e:unknown){return Response.json({error:e instanceof HttpError?e.message:"Report storage is unavailable."},{status:e instanceof HttpError?e.status:503});}
export async function GET(request:Request){try{await access();const id=new URL(request.url).searchParams.get("id");const db=getServiceSupabase();if(id){const r=await db.from("everfit_v2_reports").select("*").eq("id",id).single();if(r.error)throw r.error;return Response.json(r.data);}const r=await db.from("everfit_v2_reports").select("id,coach_name,review_date,uploaded_at").order("review_date",{ascending:false}).order("uploaded_at",{ascending:false}).limit(500);if(r.error)throw r.error;return Response.json(r.data);}catch(e){return fail(e);}}
export async function POST(request:Request){try{const user=await access();if(user.role!=="admin")throw new HttpError("Administrator access required to upload.",403);requireSameOrigin(request);if(Number(request.headers.get("content-length"))>2000000)throw new HttpError("Report exceeds 2 MB.",413);const raw=await request.text();if(Buffer.byteLength(raw)>2000000)throw new HttpError("Report exceeds 2 MB.",413);let report;try{report=parseReport(JSON.parse(raw));}catch(e){throw new HttpError((e as Error).message,400);}report.clients.sort((a,b)=>a.id.localeCompare(b.id));const hash=createHash("sha256").update(JSON.stringify(report)).digest("hex");const db=getServiceSupabase();const row=await db.from("everfit_v2_reports").upsert({coach_name:report.coach_name,review_date:report.review_date,document:report,source_hash:hash,uploaded_by:user.email},{onConflict:"source_hash",ignoreDuplicates:true}).select("id").maybeSingle();if(row.error)throw row.error;const existing=row.data??(await db.from("everfit_v2_reports").select("id").eq("source_hash",hash).single()).data;if(!existing)throw Error("Upload failed");return Response.json(existing,{status:201});}catch(e){return fail(e);}}
