"use client";
import { useEffect, useRef, useState } from "react";
import { dateShift, isGhost, metrics, parseReport, programStatus, type V2Report } from "@/lib/everfit-v2/report";
import styles from "./EverfitV2Tab.module.css";
type Entry = { id: string; coach_name: string; review_date: string; uploaded_at: string };
const pct = (n: number | null) => n === null ? "—" : `${n.toFixed(1)}%`;
async function request(url: string, init?: RequestInit) { const r = await fetch(url, { cache: "no-store", ...init }); const data = await r.json(); if (!r.ok) throw Error(data.error || "Could not load reports."); return data; }
export default function EverfitV2Tab({ isAdmin }: { isAdmin: boolean }) {
 const [entries,setEntries]=useState<Entry[]>([]), [coach,setCoach]=useState(""), [selected,setSelected]=useState(""), [report,setReport]=useState<V2Report|null>(null), [error,setError]=useState(""), [busy,setBusy]=useState(false), [loading,setLoading]=useState(true);
 const file=useRef<HTMLInputElement>(null);
 useEffect(()=>{let live=true;request("/api/coaching/everfit-v2").then(data=>{if(live){setEntries(data);setSelected(data[0]?.id||"");}}).catch(e=>{if(live)setError(e.message);}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[]);
 useEffect(()=>{let live=true;setReport(null);if(selected)request(`/api/coaching/everfit-v2?id=${encodeURIComponent(selected)}`).then(data=>{if(live)setReport(parseReport(data.document));}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[selected]);
 async function upload(f:File){setError("");setBusy(true);try{if(f.size>2000000)throw Error("Choose a report smaller than 2 MB.");const parsed=parseReport(JSON.parse(await f.text()));const saved=await request("/api/coaching/everfit-v2",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(parsed)});setEntries(await request("/api/coaching/everfit-v2"));setCoach("");setSelected(saved.id);setReport(parsed);}catch(e){setError((e as Error).message);}finally{setBusy(false);if(file.current)file.current.value="";}}
 const m=report?metrics(report):null;
 const filtered=entries.filter(e=>!coach||e.coach_name===coach);
 return <section className={styles.root}>
  <header className={styles.header}><div><h2>Everfit V2</h2><p>Weekly coach reports</p></div><div className={styles.actions}><a href="/everfit-v2-prompt.md" download>Download prompt</a>{isAdmin&&<><input ref={file} type="file" accept=".json,application/json" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);}}/><button disabled={busy} onClick={()=>file.current?.click()}>{busy?"Uploading…":"Upload report"}</button></>}</div></header>
  {error&&<p role="alert" className={styles.notice}>{error}</p>}
  {entries.length>0&&<div className={styles.filters}><select aria-label="Coach" value={coach} onChange={e=>{setCoach(e.target.value);setSelected(entries.find(r=>!e.target.value||r.coach_name===e.target.value)?.id||"");}}><option value="">All coaches</option>{[...new Set(entries.map(e=>e.coach_name))].map(c=><option key={c}>{c}</option>)}</select><select aria-label="Report" value={selected} onChange={e=>setSelected(e.target.value)}>{filtered.map(e=><option key={e.id} value={e.id}>{e.coach_name} · {e.review_date} · uploaded {new Date(e.uploaded_at).toLocaleString()}</option>)}</select></div>}
  {!report?<div className={styles.empty}>{loading?"Loading reports…":entries.length?"Loading selected report…":"Upload your first coach report to get started."}<p>One JSON report per coach. Use the Wednesday prompt to create it in Codex.</p></div>:m&&<>
   <div className={styles.heading}><h3>{report.coach_name} · {report.review_date}</h3><p>{dateShift(report.review_date,-7)} through {dateShift(report.review_date,-1)} · Asia/Karachi</p></div>
   {(!report.roster_complete||m.unknownDates.length>0||m.unknownGhosts.length>0||report.coverage_notes.length>0)&&<div className={styles.notice}><strong>Coverage</strong><p>{report.clients.length} of {report.roster_count} roster clients reviewed. {m.unknownDates.length} unknown program dates. {m.unknownGhosts.length} active clients with incomplete reply or activity evidence.</p>{report.coverage_notes.map((n,i)=><p key={i}>{n}</p>)}</div>}
   <div className={styles.cards}>{[["Roster clients",report.roster_count],["Confirmed active",m.active.length],["Confirmed ghosts",`${m.ghosts.length} · ${pct(m.ghostPct)}`],["Workout completion",pct(m.workoutPct)]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>
   <p className={styles.muted}>Ghost percentage uses reviewed active clients; missing evidence can undercount ghosts. {m.workoutMethod}; {m.workoutCoverage}/{m.active.length} active clients covered{m.workoutMethod.startsWith("Workouts")?` (${m.completed}/${m.assigned} workouts)`:""}.</p>
   <article><h3>This week</h3><p className={styles.summary}>{report.summary||"No summary provided."}</p></article>
   <div className={styles.columns}><article><h3>Retentions · {m.retentions.length}</h3><p className={styles.muted}>Next {report.retention_days} days + past 7 days</p>{m.retentions.length?m.retentions.map(c=><p key={c.id}>{c.name}<span className={styles.detail}>{dateShift(report.review_date,c.days_remaining!)} · {c.days_remaining} days remaining</span></p>):<p>None identified.</p>}</article><article><h3>Ghost clients · {m.ghosts.length}</h3>{m.ghosts.length?m.ghosts.map(c=><p key={c.id}>{c.name}</p>):<p>None confirmed.</p>}<p className={styles.muted}>Active clients with zero replies and zero recorded activity in the reporting window.</p></article></div>
   <article><h3>Clients · {report.clients.length}</h3><div className={styles.table}><table><thead><tr><th>Client</th><th>Program</th><th>Replies / activity</th><th>Workouts</th><th>Weekly notes</th></tr></thead><tbody>{report.clients.map(c=><tr key={c.id}><td>{c.name}{isGhost(c)&&<span className={styles.detail}>Ghost</span>}</td><td>{programStatus(c.days_remaining)}<span className={styles.detail}>{c.days_remaining===null?"End date unknown":`${dateShift(report.review_date,c.days_remaining)} · ${c.days_remaining} days`}</span></td><td>{c.replies_7d??"?"} / {c.activity_7d??"?"}</td><td>{c.workouts_assigned===null?pct(c.workout_pct):`${c.workouts_completed}/${c.workouts_assigned}`}</td><td>{c.summary}{c.evidence.length>0&&<details><summary>Sources</summary>{c.evidence.map((e,i)=><p key={i}>{e}</p>)}</details>}</td></tr>)}</tbody></table></div></article>
  </>}
 </section>;
}
