/**
 * Phase B3 — picker public types.
 *
 * Layer responsibilities:
 *   pickSlotsForDay : pure LLM-and-validate. Takes daily targets + build +
 *                     distribution + restrictions + variety state, returns
 *                     a structured DayPick (slot list with anchors marked)
 *                     ready for solveDay(). Owns ONE internal validation
 *                     retry; does NOT call solveDay.
 *
 *   generateWeekPlan: orchestrator. Sequentially builds 7 days, accumulates
 *                     weekly_history for variety, calls solveDay on each
 *                     day's picks, re-prompts pickSlotsForDay (with solver
 *                     feedback hint) on infeasibility / anchor degradation.
 *                     Owns the 3-call-per-day budget.
 */

import type {
  BuildSpec,
  MealDistribution,
  PlanComplexity,
} from "../types";
import type { MacroTargets } from "../../macro-calculator";
import type {
  SolveDayOutput,
  SolveDaySuccess,
  InfeasibilityError,
  ZeroedSlug,
} from "../solver";

// ============================================================================
// Picker inputs
// ============================================================================

/**
 * Solver feedback fed back into pickSlotsForDay on a re-prompt iteration.
 * Generated by the orchestrator when solveDay returns INFEASIBLE or
 * SUCCESS_WITH_DEGRADATION with anchor zeros.
 */
export interface SolverFeedback {
  kind: "infeasibility" | "anchor_degradation";
  /** Human-readable summary the LLM can use to adjust its picks. */
  message: string;
  /** Slot-specific hints. Anchor degradation populates these. */
  affected_slots?: Array<{
    slot_index: number;
    issue: string;
    /** Slug that got zeroed (anchor degradation case). */
    zeroed_anchor?: string;
  }>;
}

/**
 * Tracking state across the 7-day generation. Only ANCHOR uses count toward
 * the variety cap (per B3 spec confirmation). Side-protein appearances are
 * not taxed.
 */
export interface WeeklyHistory {
  /** Map slug → count of times used as ANCHOR in days 1..N-1. */
  anchor_use_counts: Map<string, number>;
  /** Map slug → count of times used in ANY role in days 1..N-1. Used for
   *  enforcing BuildSpec.frequency_caps (which apply to total uses). */
  total_use_counts: Map<string, number>;
  /** Names of dishes already used (for variety in plate composition).
   *  Optional — populated when the LLM provides dish names; ignored if not. */
  dish_names_used?: string[];
}

export interface DayPickInput {
  /** 1..7. */
  day_number: number;
  /** Distinguishes training day from rest day prompt-wise. */
  day_kind: "training" | "rest";
  /** Daily MacroTargets (from B1) for this day-kind. */
  targets: MacroTargets;
  buildSpec: BuildSpec;
  distribution: MealDistribution;
  /** Slugs the LLM must NOT pick (merged hard_exclude). */
  hardExclude: ReadonlySet<string>;
  /** Beginner / intermediate / advanced. */
  planComplexity: PlanComplexity;
  /** Variety state from prior days (empty on day 1). */
  weeklyHistory: WeeklyHistory;
  /** Optional: solver hint from a prior attempt's solveDay output. */
  solverFeedback?: SolverFeedback;
}

// ============================================================================
// Picker outputs
// ============================================================================

export interface PickedIngredient {
  slug: string;
  /** True for the slot's primary protein source. Exactly one per slot. */
  isAnchor: boolean;
}

export interface PickedSlot {
  /** 1-based, matches MealDistribution.slots[i].index. */
  index: number;
  ingredients: PickedIngredient[];
}

export interface DayPick {
  day: number;
  day_kind: "training" | "rest";
  slots: PickedSlot[];
  /** How many LLM calls were used to produce this pick (1 or 2). */
  llm_calls_used: number;
  /** True if the picker had to retry once on validation failure. */
  retried: boolean;
}

export interface PickError {
  type: "PICK_ERROR";
  /** Why the picker gave up. */
  reason: string;
  /** What we asked for, for debugging. */
  day_number: number;
  /** All validation issues from the final attempt — surface to coach. */
  violations: PickViolation[];
  /** Total LLM calls burned before giving up. */
  llm_calls_used: number;
}

export interface PickViolation {
  kind:
    | "invalid_slug"
    | "excluded_slug"
    | "missing_anchor"
    | "multiple_anchors"
    | "wrong_slot_count"
    | "complexity_cap_exceeded"
    | "empty_slot"
    | "json_parse_failed"
    | "missing_field"
    /**
     * B6a-pivot: emitted by the deterministic template picker when an
     * ingredient's swap_chain is fully exhausted by the client's
     * hardExclude set. Carries the full walked path in `message`.
     */
    | "swap_chain_exhausted";
  slot_index?: number;
  slug?: string;
  message: string;
}

export type PickResult = DayPick | PickError;

// ============================================================================
// LLM client interface (mockable for tests)
// ============================================================================

/**
 * Minimal interface the picker needs from an LLM. Tests inject a mock that
 * returns canned responses. Production wiring uses the AnthropicLLMClient
 * defined in llm-client.ts.
 */
export interface LLMClient {
  /**
   * Run one LLM call. Returns the assistant's text response.
   *
   * The picker passes a system prompt + a user prompt; the LLM should
   * return JSON matching DayPick's slot structure (validation happens
   * downstream in pickSlotsForDay).
   */
  complete(args: {
    system: string;
    user: string;
    /** For debugging/logging. */
    label?: string;
  }): Promise<string>;
}

// ============================================================================
// Orchestrator (generateWeekPlan) types
// ============================================================================

/**
 * Per-day diagnostics emitted by the orchestrator. Surfaced in
 * GenerationDiagnostics for observability (post-B3 measurement).
 */
export interface DayDiagnostics {
  day_number: number;
  day_kind: "training" | "rest";
  /** 1, 2, or 3 — counts every LLM call (initial + re-prompts). */
  llm_calls_used: number;
  /** Whether any anchor-degradation re-prompt fired. */
  anchor_reprompt_fired: boolean;
  /** Whether any infeasibility re-prompt fired. */
  infeasibility_reprompt_fired: boolean;
  /** Final solver outcome. */
  solver_status: "SUCCESS" | "SUCCESS_WITH_DEGRADATION" | "INFEASIBLE";
  /** Wall-clock from start of day's picker call to final solver decision. */
  total_wall_clock_ms: number;
  /** Solver's per-day fallback level if successful. */
  solver_fallback_level?: 10 | 15 | 20;
  /** List of zeroed slugs (anchor or non-anchor) from the final solver run. */
  zeroed_slugs: ZeroedSlug[];
}

export interface GenerationDiagnostics {
  per_day: DayDiagnostics[];
  /** Total LLM calls across the week. */
  total_llm_calls: number;
  /** Wall-clock for the whole 7-day generation. */
  total_wall_clock_ms: number;
  /** How many days needed re-prompts of any kind. */
  days_with_reprompts: number;
  /** How many days hit ±15% or ±20% solver fallback. */
  days_with_solver_fallback: number;
  /** How many days returned infeasibility. */
  days_infeasible: number;
}

export interface WeekPlanInput {
  /** Optional: training-day macros (from B1). Defaults to all days = training. */
  trainingTargets: MacroTargets;
  /** Rest-day macros (from B1). Required even for builds that don't cycle. */
  restTargets: MacroTargets;
  /**
   * Per-day kind override. Index 0 = day 1, etc. Length must be 7.
   * If absent, defaults to all 7 days as "training".
   */
  dayKinds?: ReadonlyArray<"training" | "rest">;
  buildSpec: BuildSpec;
  /** Same distribution for every day (for non-endurance). For endurance, this
   *  is the training-day distribution; rest-day distribution is read from
   *  the build's allowed_distributions per the rest-day fallback. */
  distribution: MealDistribution;
  /** Optional rest-day-specific distribution (for endurance). If absent,
   *  rest days reuse `distribution`. */
  restDistribution?: MealDistribution;
  hardExclude: ReadonlySet<string>;
  planComplexity: PlanComplexity;
}

export interface WeekPlanSuccess {
  status: "SUCCESS";
  /** 7 days, each with the final solver result. */
  days: Array<{
    day: number;
    day_kind: "training" | "rest";
    pick: DayPick;
    solve: SolveDaySuccess;
    /** Daily macro targets used for this day. Attached by orchestrator
     *  for downstream audit / PDF render; identical to the targets passed
     *  into solveDay for this day. */
    targets: MacroTargets;
    /** Per-day distribution (matters for endurance which switches between
     *  training-day and rest-day distributions). */
    distribution: MealDistribution;
    /**
     * Optional template-derived metadata for downstream consumers (PDF
     * adapter). Populated by the deterministic template orchestrator
     * (B6a-pivot). Not populated by the LLM picker path — that path
     * leaves this undefined and the adapter falls back to no dish name.
     */
    template_meta?: {
      /**
       * Map from slot.index → authored dish_name string. Keyed by index
       * (not array position) so it works cleanly with non-contiguous slot
       * layouts (e.g. Endurance rest days with fewer slots than training).
       */
      slot_dish_names: Record<number, string>;
    };
  }>;
  diagnostics: GenerationDiagnostics;
}

export interface WeekPlanFailure {
  status: "FAILURE";
  /** Reason the week couldn't complete. */
  reason: string;
  /** Day numbers that failed. */
  failed_days: number[];
  /** Per-day partial results — successful days included; failed days
   *  have the picker error or infeasibility populated. */
  days: Array<{
    day: number;
    day_kind: "training" | "rest";
    pick?: DayPick;
    solve?: SolveDayOutput;
    pickError?: PickError;
  }>;
  diagnostics: GenerationDiagnostics;
}

export type WeekPlanOutput = WeekPlanSuccess | WeekPlanFailure;

// ============================================================================
// Type guards
// ============================================================================

export function isPickError(r: PickResult): r is PickError {
  return (r as PickError).type === "PICK_ERROR";
}

export function isWeekPlanSuccess(r: WeekPlanOutput): r is WeekPlanSuccess {
  return r.status === "SUCCESS";
}

// Re-exports
export type {
  BuildSpec,
  MacroTargets,
  MealDistribution,
  PlanComplexity,
  SolveDayOutput,
  SolveDaySuccess,
  InfeasibilityError,
  ZeroedSlug,
};
